mkdir /tmp/"File:	/Users/sarnobat/sarnobat.git/gedcom/rohidekar.ged"
mkdir /tmp/"Name:	Prakash"
mkdir /tmp/"positional args:  []"
mkdir /tmp/"individual: Hanumanth Rao Rohidekar (b. 21 Aug 1921, d. 9 Feb 2000)"
mkdir /tmp/"individual: Sumitra/Geetabai Dani Dani/ (d. 16 Mar 2000)"
mkdir /tmp/"individual: Vinod Rohidekar (b. 19 Apr 57)"
mkdir /tmp/"individual: Vidya Rohidekar (b. 28 Sep 10)"
mkdir /tmp/"individual: Vilas Rohidekar (b. 2 Feb 1961)"
mkdir /tmp/"individual: Veena Rohidekar (b. 4 May 1964)"
mkdir /tmp/"individual: Vijay Rohidekar (b. 2 Feb 1966)"
mkdir /tmp/"individual: Vasanthi Rohidekar (b. 15 Feb 1970)"
mkdir /tmp/"individual: Vasudha Kadiyali"
mkdir /tmp/"individual: Vibhas Rohidekar (b. 1985)"
mkdir /tmp/"individual: Vandita Rohidekar (b. 1992)"
mkdir /tmp/"individual: Vaman Simha (b. 28 Sep 1956)"
mkdir /tmp/"individual: Meghana Simha (b. 14 Aug 1984)"
mkdir /tmp/"individual: Tejashree Simha (b. 1 Mar 1989)"
mkdir /tmp/"individual: Usha S. G (b. 20 Aug 1968)"
mkdir /tmp/"individual: Jayaprakash Veena Jayaprakash (b. 2 Nov 19)"
mkdir /tmp/"individual: Anuradha Kulkarni"
mkdir /tmp/"individual: Poorvi Rohidekar (b. 21 Oct 1998)"
mkdir /tmp/"individual: Varsha Rohidekar (b. 6 Jul 2003)"
mkdir /tmp/"individual: Vasudevan"
mkdir /tmp/"individual: Vallabh Vasudevan"
mkdir /tmp/"individual: Vaibhav Vasudevan"
mkdir /tmp/"individual: Ketaki Jayaprakash (b. 1997)"
mkdir /tmp/"individual: Laxman Rao Rohidekar (b. 1847, d. 1934)"
mkdir /tmp/"individual: Sitabai"
mkdir /tmp/"individual: Venkat Rao Rohidekar (b. 1825)"
mkdir /tmp/"individual: Tarabai (b. 1828, d. 1926)"
mkdir /tmp/"individual: Anand Rao Rohidekar (d. 1895)"
mkdir /tmp/"individual: Bhimka Rao Rohidekar (d. 1920)"
mkdir /tmp/"individual: Venkawwa Rohidekar"
mkdir /tmp/"individual: Venkatesh Rohidekar (b. 1889, d. 1906)"
mkdir /tmp/"individual: Venkubai Mirji (b. 1905)"
mkdir /tmp/"individual: Rangubai Padki (b. 1894)"
mkdir /tmp/"individual: Raghunath Rao Rohidekar (b. 1893, d. 1949)"
mkdir /tmp/"individual: Janaki Kodagli (b. 1899, d. 1955)"
mkdir /tmp/"individual: Krishnaji Laxman Rohidekar (b. 1899, d. 1964)"
mkdir /tmp/"individual: Venkubai (b. 1905, d. 1945)"
mkdir /tmp/"individual: Ramachandra Rao Rohidekar (b. 1912, d. 1984)"
mkdir /tmp/"individual: Shamaji Rao Rohidekar (b. 15 Sep 1915)"
mkdir /tmp/"individual: Bhagavanth Rao Rohidekar (b. Bet. 5 and 1918)"
mkdir /tmp/"individual: Srinivas Rohidekar (b. 1923, d. 1930)"
mkdir /tmp/"individual: Godavari Rohidekar (b. 1925, d. 1980)"
mkdir /tmp/"individual: Vatsala Rohidekar (b. 1928, d. 1953)"
mkdir /tmp/"individual: Sitabai Anikhindi (d. 1987)"
mkdir /tmp/"individual: Laxmibai Rama (d. 1983)"
mkdir /tmp/"individual: Ravindra Rohidekar (b. 1947, d. 2000)"
mkdir /tmp/"individual: Meenakshi Rohidekar (b. 1950)"
mkdir /tmp/"individual: Deepak Rohidekar (b. 1964)"
mkdir /tmp/"individual: Anupama"
mkdir /tmp/"individual: Snehalata Rao"
mkdir /tmp/"individual: Gautham Rohidekar (b. 1975)"
mkdir /tmp/"individual: Puneet Rohidekar (b. 1981)"
mkdir /tmp/"individual: Gaurav Rohidekar"
mkdir /tmp/"individual: Renubai"
mkdir /tmp/"individual: Krishna/Shantabai Talikoti Talikoti/ (d. 1995)"
mkdir /tmp/"individual: Manjula Rohidekar"
mkdir /tmp/"individual: Parimala Rohidekar"
mkdir /tmp/"individual: Sham Gombi"
mkdir /tmp/"individual: Anand Rohidekar"
mkdir /tmp/"individual: Venkatesh Rohidekar"
mkdir /tmp/"individual: Madhav Rohidekar"
mkdir /tmp/"individual: Vidya Rao"
mkdir /tmp/"individual: Bhavana Rohidekar (b. 1989)"
mkdir /tmp/"individual: Muralidhar Addabaddi"
mkdir /tmp/"individual: Suresh Addabaddi"
mkdir /tmp/"individual: Sulabha/Shuba Rao Addabaddi Addabaddi/"
mkdir /tmp/"individual: Sarala Addabaddi"
mkdir /tmp/"individual: Rohidekar (d. 1963)"
mkdir /tmp/"individual: Tulsakka Rohidekar (b. 1916)"
mkdir /tmp/"individual: Susheela Rohidekar (b. 1922, d. 1926)"
mkdir /tmp/"individual: Champakkabai Rohidekar (b. 1920, d. 1998)"
mkdir /tmp/"individual: Ranga Rao Rohidekar (b. 1924)"
mkdir /tmp/"individual: Vasant Rao Rohidekar (b. 1932)"
mkdir /tmp/"individual: Babu Rao Rohidekar (b. 1932)"
mkdir /tmp/"individual: Raghavendra (Raghu) Rohidekar (b. 1934)"
mkdir /tmp/"individual: Vaman Rao Mirji (d. 1965)"
mkdir /tmp/"individual: Narayana Rao Raghavendra Habbu (b. 1914, d. 1989)"
mkdir /tmp/"individual: Shankuntala Potdar"
mkdir /tmp/"individual: Kaveri Parvatikar"
mkdir /tmp/"individual: Mirji/Shantabai Shantabai/"
mkdir /tmp/"individual: Malati Kakmari"
mkdir /tmp/"individual: Radhabai"
mkdir /tmp/"individual: Raghavendra Jagirdar"
mkdir /tmp/"individual: Sudhir Sarnobat (b. 1946)"
mkdir /tmp/"individual: Srinivas Rohidekar"
mkdir /tmp/"individual: (stillborn) Rohidekar"
mkdir /tmp/"individual: Shamsundar Bengeri"
mkdir /tmp/"individual: Latha Kulkarni"
mkdir /tmp/"individual: Vatsala/Vijaya Kshirsagar Kshirsagar/"
mkdir /tmp/"individual: Surendra Muthalik"
mkdir /tmp/"individual: Jyothi Addabaddi"
mkdir /tmp/"individual: Dattatreya Pujar"
mkdir /tmp/"individual: Prakash Sarnobat (b. 1978)"
mkdir /tmp/"individual: Sridhar Sarnobat (b. 1982)"
mkdir /tmp/"individual: Priya Sarnobat (b. 1989)"
mkdir /tmp/"individual: Puttaka Rohidekar"
mkdir /tmp/"individual: Lallakka Rohidekar"
mkdir /tmp/"individual: Narsimhamurthy DP"
mkdir /tmp/"individual: Chakarapani Bangalore Krishnaswamny (d. 2009)"
mkdir /tmp/"individual: Ranganath/Gopal Rohidekar Rohidekar/"
mkdir /tmp/"individual: Radha"
mkdir /tmp/"individual: Nirmala/Asha Rohidekar Rohidekar/"
mkdir /tmp/"individual: Jayaraj Rohidekar"
mkdir /tmp/"individual: Prema Rohidekar"
mkdir /tmp/"individual: Ashok Sadarjoshi"
mkdir /tmp/"individual: Prakash Kulkarni"
mkdir /tmp/"individual: Pushpa"
mkdir /tmp/"individual: (no name)"
mkdir /tmp/"individual: (no name)"
mkdir /tmp/"individual: (no name)"
mkdir /tmp/"individual: (no name)"
mkdir /tmp/"individual: (no name)"
mkdir /tmp/"individual: (no name)"
mkdir /tmp/"individual: Usha"
mkdir /tmp/"individual: Jinki Prema"
mkdir /tmp/"individual: Ramesh R Habbu (d. 2000)"
mkdir /tmp/"individual: Ramesh"
mkdir /tmp/"individual: Sudha/'Baby' 'Baby' 'Baby'/"
mkdir /tmp/"individual: Vijaya / Viji Viji / Viji //"
mkdir /tmp/"individual: Sridhar Rohidekar"
mkdir /tmp/"individual: Gururaj Rohidekar"
mkdir /tmp/"individual: Veena Rohidekar"
mkdir /tmp/"individual: Anjana"
mkdir /tmp/"individual: Manjula Benkai"
mkdir /tmp/"individual: Vasant Nagsampige"
mkdir /tmp/"individual: Sreenivas Rohidekar"
mkdir /tmp/"individual: Venkatesh Rohidekar"
mkdir /tmp/"individual: Venkana"
mkdir /tmp/"individual: Rupa Rohidekar"
mkdir /tmp/"individual: Satish Rohidekar"
mkdir /tmp/"individual: Indumati Rohidekar"
mkdir /tmp/"individual: Krishnamurthy Rohidekar"
mkdir /tmp/"individual: Govindaswamy"
mkdir /tmp/"individual: Chitra Srinivasan"
mkdir /tmp/"individual: Krishnamurthy"
mkdir /tmp/"individual: Lakshmi"
mkdir /tmp/"individual: Madhavi"
mkdir /tmp/"individual: Jeevan Bharadhwaj DN"
mkdir /tmp/"individual: Pujitha Nagarajan"
mkdir /tmp/"individual: Shreeneedhi DN"
mkdir /tmp/"individual: Narayan K (b. 1980)"
mkdir /tmp/"individual: Tejasvi N Rao"
mkdir /tmp/"individual: Rajiva Rohidekar"
mkdir /tmp/"individual: Rahul Rohidekar"
mkdir /tmp/"individual: Prasanna Kulkarni"
mkdir /tmp/"individual: Poornima Kulkarni"
mkdir /tmp/"individual: Megha Bengeri"
mkdir /tmp/"individual: Amit Bengeri"
mkdir /tmp/"individual: Soudamini Gombi (b. 1984)"
mkdir /tmp/"individual: Sindu Gombi (b. 1991)"
mkdir /tmp/"individual: Yoga"
mkdir /tmp/"individual: Sandeep ('Peetu') Addabaddi"
mkdir /tmp/"individual: Sagar Addabaddi (b. 1980)"
mkdir /tmp/"individual: Archana Muthalik"
mkdir /tmp/"individual: Vandana Muthalik"
mkdir /tmp/"individual: Meghana Muthalik"
mkdir /tmp/"individual: Vishal Pujar"
mkdir /tmp/"individual: Anagha Pujar"
mkdir /tmp/"individual: (no name)"
mkdir /tmp/"individual: (no name)"
mkdir /tmp/"individual: Sameer Rohidekar"
mkdir /tmp/"individual: Kiran Rohidekar (b. 1990)"
mkdir /tmp/"individual: Gauri Rohidekar (b. 1996)"
mkdir /tmp/"individual: Rashmi Govind (b. 1985)"
mkdir /tmp/"individual: Ramya Govind (b. 1988)"
mkdir /tmp/"individual: Dilip Krishnamurthy (b. 1990)"
mkdir /tmp/"individual: Akhil Rohidekar"
mkdir /tmp/"individual: Nikhil Rohidekar"
mkdir /tmp/"individual: Gururaj Beloli"
mkdir /tmp/"individual: Amit Umrani"
mkdir /tmp/"individual: Anuraddha Rohidekar"
mkdir /tmp/"individual: Rohini Rohidekar"
mkdir /tmp/"individual: Shree Rohidekar"
mkdir /tmp/"individual: Sudharshan Harihar"
mkdir /tmp/"individual: Vaman Rao (d. 2014)"
mkdir /tmp/"individual: Suma Sudharshan"
mkdir /tmp/"individual: Rashmi"
mkdir /tmp/"individual: Sanvi"
mkdir /tmp/"individual: Amruta"
mkdir /tmp/"individual: Vijaya Sadarjoshi"
mkdir /tmp/"individual: Ajay Rohidekar"
mkdir /tmp/"individual: Jagdish"
mkdir /tmp/"individual: Varada"
mkdir /tmp/"individual: Durgaprasad Bilagi"
mkdir /tmp/"individual: Kush"
mkdir /tmp/"individual: (no name)"
mkdir /tmp/"individual: Raghavendra Rao S"
mkdir /tmp/"individual: Beloli"
mkdir /tmp/"individual: Beloli"
mkdir /tmp/"individual: (no name)"
mkdir /tmp/"individual: (no name)"
mkdir /tmp/"individual: Vasanthi ‘Bhagi’ Harish"
mkdir /tmp/"individual: K Harish"
mkdir /tmp/"individual: K H Anirudh"
mkdir /tmp/"individual: Appu"
mkdir /tmp/"individual: (no name)"
mkdir /tmp/"individual: Anil"
mkdir /tmp/"individual: Dr M V Mahishi"
mkdir /tmp/"individual: Ravindra / Anil? Anil? / Anil? // (d. 2010)"
mkdir /tmp/"individual: Appu"
mkdir /tmp/"individual: Anil (d. 2010)"
mkdir /tmp/"individual: Snehalata / Appu Appu / Appu //"
mkdir /tmp/"individual: Vinayak Desai"
mkdir /tmp/"individual: Gururajachav"
mkdir /tmp/"individual: Archana Kulkarni"
mkdir /tmp/"individual: Shashidar Kulkarni"
mkdir /tmp/"individual: Aghamya Kulkarni"
mkdir /tmp/"individual: Arvind MG"
mkdir /tmp/"individual: Pralad Rao Wai"
mkdir /tmp/"individual: Dr Anand Rao"
mkdir /tmp/"individual: Prakash"
mkdir /tmp/"individual: Sharad Rohidekar (b. 1993)"
mkdir /tmp/"individual: Ashwini Rohidekar (b. 7 Apr 1996)"
mkdir /tmp/"individual: Pramod Nagsampige"
mkdir /tmp/"individual: Pavan Nagsampige"
mkdir /tmp/"individual: Uday Savadatti"
mkdir /tmp/"individual: Giridhar Deshpande"
mkdir /tmp/"individual: Aishwarya Deshpande"
mkdir /tmp/"individual: Girish Dixit"
mkdir /tmp/"individual: Shashank"
mkdir /tmp/"individual: Nishant"
mkdir /tmp/"individual: Raghavendra"
mkdir /tmp/"individual: Vishnu"
mkdir /tmp/"individual: Hariprasad"
mkdir /tmp/"individual: Minaz Sajan"
mkdir /tmp/"individual: Sahir"
mkdir /tmp/"individual: Addabaddi"
mkdir /tmp/"individual: Habbu"
mkdir /tmp/"individual: (no name)"
mkdir /tmp/"individual: Habbu"
mkdir /tmp/"individual: Dr Rajini"
mkdir /tmp/"individual: Sapna Desai"
mkdir /tmp/"individual: Sonali Desai"
mkdir /tmp/"individual: Paavni"
mkdir /tmp/"individual: Leela"
mkdir /tmp/"individual: Rashmi"
mkdir /tmp/"individual: Vani"
mkdir /tmp/"individual: Koushik"
mkdir /tmp/"individual: Dr Prathibha"
mkdir /tmp/"individual: Siddhanth Rao"
mkdir /tmp/"individual: Rao"
mkdir /tmp/"individual: (no name)"
mkdir /tmp/"individual: (no name)"
mkdir /tmp/"individual: (no name)"
mkdir /tmp/"individual: Joshua Vallis"
mkdir /tmp/"individual: Jaguar Vallis"
mkdir /tmp/"individual: (no name)"
mkdir /tmp/"individual: Swaraat Bilagi"
mkdir /tmp/"individual: Madan"
mkdir /tmp/"individual: Addabaddi"
mkdir /tmp/"individual: Bengeri"
mkdir /tmp/"individual: (no name)"
mkdir /tmp/"individual: Suhas Harihar"
mkdir /tmp/"individual: Ritinder Kaur"
mkdir /tmp/"individual: Harihar"
mkdir /tmp/"individual: Rashmi"
mkdir /tmp/"individual: Rohidekar (b. 17 Feb 2021)"
mkdir /tmp/"individual: Rohidekar"
mkdir /tmp/"individual: Bilagi (b. 20 Feb 2021)"
mkdir /tmp/"individual: Mishka Sajan"
mkdir /tmp/"individual: Bharadhwaj DN"
mkdir /tmp/"individual: Bharadhwaj DN"
mkdir /tmp/"individual: Darshan Gogga"
mkdir /tmp/"individual: (no name) (b. 2 Nov 2020)"
mkdir /tmp/"individual: Dhruti Ramya (b. 1995)"
mkdir /tmp/"individual: Geeta Rohidekar"
mkdir /tmp/"individual: delete this"
mkdir /tmp/"individual: Nalini Rohidekar"
mkdir /tmp/"individual: Panchamukhi"
mkdir /tmp/"individual: Megha Panchmukhi"
mkdir /tmp/"individual: Arun Bellubbi"
mkdir /tmp/"individual: Ajay Bellubbi"
mkdir /tmp/"individual: Sunita"
mkdir /tmp/"individual: Rakshank Savadatti"
mkdir /tmp/"individual: Rohit Savadatti"
mkdir /tmp/"individual: Vineeth (b. 1982)"
mkdir /tmp/"Hanumanth Rao Rohidekar (b. 21 Aug 1921, d. 9 Feb 2000) ⚭ Sumitra/Geetabai Dani Dani/ (d. 16 Mar 2000)"
mkdir /tmp/"unique identifier: d2dbf014-f1ec-464e-b4dc-3da7300cb799"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Hanumanth Rao Rohidekar (b. 21 Aug 1921, d. 9 Feb 2000) :: Hanumanth Rao Rohidekar (b. 21 Aug 1921, d. 9 Feb 2000) ⚭ Sumitra/Geetabai Dani Dani/ (d. 16 Mar 2000)"
mkdir /tmp/"[DEBUG] Sumitra/Geetabai Dani Dani/ (d. 16 Mar 2000) :: Hanumanth Rao Rohidekar (b. 21 Aug 1921, d. 9 Feb 2000) ⚭ Sumitra/Geetabai Dani Dani/ (d. 16 Mar 2000)"
mkdir /tmp/"Vinod Rohidekar (b. 19 Apr 57) ⚭ Vasudha Kadiyali"
mkdir /tmp/"unique identifier: ee41b21a-4d4e-4ade-8284-1de9ddaffd73"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Vinod Rohidekar (b. 19 Apr 57) :: Vinod Rohidekar (b. 19 Apr 57) ⚭ Vasudha Kadiyali"
mkdir /tmp/"[DEBUG] Vasudha Kadiyali :: Vinod Rohidekar (b. 19 Apr 57) ⚭ Vasudha Kadiyali"
mkdir /tmp/"Vaman Simha (b. 28 Sep 1956) ⚭ Vidya Rohidekar (b. 28 Sep 10)"
mkdir /tmp/"unique identifier: c6eca5a7-fc22-465d-9241-b8f286b3a60d"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Vaman Simha (b. 28 Sep 1956) :: Vaman Simha (b. 28 Sep 1956) ⚭ Vidya Rohidekar (b. 28 Sep 10)"
mkdir /tmp/"[DEBUG] Vidya Rohidekar (b. 28 Sep 10) :: Vaman Simha (b. 28 Sep 1956) ⚭ Vidya Rohidekar (b. 28 Sep 10)"
mkdir /tmp/"Vilas Rohidekar (b. 2 Feb 1961) ⚭ Usha S. G (b. 20 Aug 1968)"
mkdir /tmp/"unique identifier: 8af1ea9f-62e5-4613-85c1-3461ac9c209e"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Vilas Rohidekar (b. 2 Feb 1961) :: Vilas Rohidekar (b. 2 Feb 1961) ⚭ Usha S. G (b. 20 Aug 1968)"
mkdir /tmp/"[DEBUG] Usha S. G (b. 20 Aug 1968) :: Vilas Rohidekar (b. 2 Feb 1961) ⚭ Usha S. G (b. 20 Aug 1968)"
mkdir /tmp/"Jayaprakash Veena Jayaprakash (b. 2 Nov 19) ⚭ Veena Rohidekar (b. 4 May 1964)"
mkdir /tmp/"unique identifier: b12287e7-7e60-4c45-854a-ff5aef9a1c88"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Jayaprakash Veena Jayaprakash (b. 2 Nov 19) :: Jayaprakash Veena Jayaprakash (b. 2 Nov 19) ⚭ Veena Rohidekar (b. 4 May 1964)"
mkdir /tmp/"[DEBUG] Veena Rohidekar (b. 4 May 1964) :: Jayaprakash Veena Jayaprakash (b. 2 Nov 19) ⚭ Veena Rohidekar (b. 4 May 1964)"
mkdir /tmp/"Vijay Rohidekar (b. 2 Feb 1966) ⚭ Anuradha Kulkarni"
mkdir /tmp/"unique identifier: 29406981-0783-480d-9356-1ea29911adcf"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Vijay Rohidekar (b. 2 Feb 1966) :: Vijay Rohidekar (b. 2 Feb 1966) ⚭ Anuradha Kulkarni"
mkdir /tmp/"[DEBUG] Anuradha Kulkarni :: Vijay Rohidekar (b. 2 Feb 1966) ⚭ Anuradha Kulkarni"
mkdir /tmp/"Vasudevan ⚭ Vasanthi Rohidekar (b. 15 Feb 1970)"
mkdir /tmp/"unique identifier: 3f9285ec-f493-4e2c-8c46-38968afa3120"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Vasudevan :: Vasudevan ⚭ Vasanthi Rohidekar (b. 15 Feb 1970)"
mkdir /tmp/"[DEBUG] Vasanthi Rohidekar (b. 15 Feb 1970) :: Vasudevan ⚭ Vasanthi Rohidekar (b. 15 Feb 1970)"
mkdir /tmp/"Laxman Rao Rohidekar (b. 1847, d. 1934) ⚭ Renubai"
mkdir /tmp/"unique identifier: d24b0564-1d9a-49b8-92de-9c381bf659a9"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Laxman Rao Rohidekar (b. 1847, d. 1934) :: Laxman Rao Rohidekar (b. 1847, d. 1934) ⚭ Renubai"
mkdir /tmp/"[DEBUG] Renubai :: Laxman Rao Rohidekar (b. 1847, d. 1934) ⚭ Renubai"
mkdir /tmp/"Laxman Rao Rohidekar (b. 1847, d. 1934) ⚭ Sitabai"
mkdir /tmp/"unique identifier: d24b0564-1d9a-49b8-92de-9c381bf659a9"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Laxman Rao Rohidekar (b. 1847, d. 1934) :: Laxman Rao Rohidekar (b. 1847, d. 1934) ⚭ Sitabai"
mkdir /tmp/"[DEBUG] Sitabai :: Laxman Rao Rohidekar (b. 1847, d. 1934) ⚭ Sitabai"
mkdir /tmp/"Venkat Rao Rohidekar (b. 1825) ⚭ Tarabai (b. 1828, d. 1926)"
mkdir /tmp/"unique identifier: 799db437-e0d2-44cc-a8f9-afda533cb5b7"
mkdir /tmp/""
mkdir /tmp/"Found Root"
mkdir /tmp/"[DEBUG] Venkat Rao Rohidekar (b. 1825) :: Venkat Rao Rohidekar (b. 1825) ⚭ Tarabai (b. 1828, d. 1926)"
mkdir /tmp/"[DEBUG] Tarabai (b. 1828, d. 1926) :: Venkat Rao Rohidekar (b. 1825) ⚭ Tarabai (b. 1828, d. 1926)"
mkdir /tmp/"Venkatesh Rohidekar (b. 1889, d. 1906) ⚭ Rangubai Padki (b. 1894)"
mkdir /tmp/"unique identifier: 991e59fd-d5dd-48c9-a3a3-1f41b3c33b9d"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Venkatesh Rohidekar (b. 1889, d. 1906) :: Venkatesh Rohidekar (b. 1889, d. 1906) ⚭ Rangubai Padki (b. 1894)"
mkdir /tmp/"[DEBUG] Rangubai Padki (b. 1894) :: Venkatesh Rohidekar (b. 1889, d. 1906) ⚭ Rangubai Padki (b. 1894)"
mkdir /tmp/"Raghunath Rao Rohidekar (b. 1893, d. 1949) ⚭ Janaki Kodagli (b. 1899, d. 1955)"
mkdir /tmp/"unique identifier: cbe75ff9-0c89-49dc-9617-3b55a4672530"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Raghunath Rao Rohidekar (b. 1893, d. 1949) :: Raghunath Rao Rohidekar (b. 1893, d. 1949) ⚭ Janaki Kodagli (b. 1899, d. 1955)"
mkdir /tmp/"[DEBUG] Janaki Kodagli (b. 1899, d. 1955) :: Raghunath Rao Rohidekar (b. 1893, d. 1949) ⚭ Janaki Kodagli (b. 1899, d. 1955)"
mkdir /tmp/"Krishnaji Laxman Rohidekar (b. 1899, d. 1964) ⚭ Venkubai (b. 1905, d. 1945)"
mkdir /tmp/"unique identifier: 59f8af2e-5930-4a1b-9421-6acf5929a052"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Krishnaji Laxman Rohidekar (b. 1899, d. 1964) :: Krishnaji Laxman Rohidekar (b. 1899, d. 1964) ⚭ Venkubai (b. 1905, d. 1945)"
mkdir /tmp/"[DEBUG] Venkubai (b. 1905, d. 1945) :: Krishnaji Laxman Rohidekar (b. 1899, d. 1964) ⚭ Venkubai (b. 1905, d. 1945)"
mkdir /tmp/"Ramachandra Rao Rohidekar (b. 1912, d. 1984) ⚭ Sitabai Anikhindi (d. 1987)"
mkdir /tmp/"unique identifier: 6e6d46f7-c1bb-4bf0-9630-fbafdc8dfe90"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Ramachandra Rao Rohidekar (b. 1912, d. 1984) :: Ramachandra Rao Rohidekar (b. 1912, d. 1984) ⚭ Sitabai Anikhindi (d. 1987)"
mkdir /tmp/"[DEBUG] Sitabai Anikhindi (d. 1987) :: Ramachandra Rao Rohidekar (b. 1912, d. 1984) ⚭ Sitabai Anikhindi (d. 1987)"
mkdir /tmp/"Shamaji Rao Rohidekar (b. 15 Sep 1915) ⚭ Laxmibai Rama (d. 1983)"
mkdir /tmp/"unique identifier: 321b1937-339c-4151-982b-7909f8fac87b"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Shamaji Rao Rohidekar (b. 15 Sep 1915) :: Shamaji Rao Rohidekar (b. 15 Sep 1915) ⚭ Laxmibai Rama (d. 1983)"
mkdir /tmp/"[DEBUG] Laxmibai Rama (d. 1983) :: Shamaji Rao Rohidekar (b. 15 Sep 1915) ⚭ Laxmibai Rama (d. 1983)"
mkdir /tmp/"Deepak Rohidekar (b. 1964) ⚭ Anupama"
mkdir /tmp/"unique identifier: bcc5dd56-3260-4507-b81e-79eee25bffc9"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Deepak Rohidekar (b. 1964) :: Deepak Rohidekar (b. 1964) ⚭ Anupama"
mkdir /tmp/"[DEBUG] Anupama :: Deepak Rohidekar (b. 1964) ⚭ Anupama"
mkdir /tmp/"Ravindra Rohidekar (b. 1947, d. 2000) ⚭ Snehalata Rao"
mkdir /tmp/"unique identifier: b15e6029-b32a-4fe3-bf4c-ba4665c90dc7"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Ravindra Rohidekar (b. 1947, d. 2000) :: Ravindra Rohidekar (b. 1947, d. 2000) ⚭ Snehalata Rao"
mkdir /tmp/"[DEBUG] Snehalata Rao :: Ravindra Rohidekar (b. 1947, d. 2000) ⚭ Snehalata Rao"
mkdir /tmp/"Bhagavanth Rao Rohidekar (b. Bet. 5 and 1918) ⚭ Krishna/Shantabai Talikoti Talikoti/ (d. 1995)"
mkdir /tmp/"unique identifier: 513d45a3-dc5e-47ef-9225-d9367457a729"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Bhagavanth Rao Rohidekar (b. Bet. 5 and 1918) :: Bhagavanth Rao Rohidekar (b. Bet. 5 and 1918) ⚭ Krishna/Shantabai Talikoti Talikoti/ (d. 1995)"
mkdir /tmp/"[DEBUG] Krishna/Shantabai Talikoti Talikoti/ (d. 1995) :: Bhagavanth Rao Rohidekar (b. Bet. 5 and 1918) ⚭ Krishna/Shantabai Talikoti Talikoti/ (d. 1995)"
mkdir /tmp/"Sham Gombi ⚭ Parimala Rohidekar"
mkdir /tmp/"unique identifier: 7e01d76e-43b6-4b6a-89b7-4628e009617c"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Sham Gombi :: Sham Gombi ⚭ Parimala Rohidekar"
mkdir /tmp/"[DEBUG] Parimala Rohidekar :: Sham Gombi ⚭ Parimala Rohidekar"
mkdir /tmp/"Anand Rohidekar ⚭ Vidya Rao"
mkdir /tmp/"unique identifier: 26dab686-0738-43e8-8868-57e7d634351c"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Anand Rohidekar :: Anand Rohidekar ⚭ Vidya Rao"
mkdir /tmp/"[DEBUG] Vidya Rao :: Anand Rohidekar ⚭ Vidya Rao"
mkdir /tmp/"Muralidhar Addabaddi ⚭ Godavari Rohidekar (b. 1925, d. 1980)"
mkdir /tmp/"unique identifier: 063b0ce2-045d-486f-befe-07c7a41f3249"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Muralidhar Addabaddi :: Muralidhar Addabaddi ⚭ Godavari Rohidekar (b. 1925, d. 1980)"
mkdir /tmp/"[DEBUG] Godavari Rohidekar (b. 1925, d. 1980) :: Muralidhar Addabaddi ⚭ Godavari Rohidekar (b. 1925, d. 1980)"
mkdir /tmp/"Vaman Rao Mirji (d. 1965) ⚭ Tulsakka Rohidekar (b. 1916)"
mkdir /tmp/"unique identifier: 7e4faa68-534d-401c-ad79-0b6a5c4c026e"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Vaman Rao Mirji (d. 1965) :: Vaman Rao Mirji (d. 1965) ⚭ Tulsakka Rohidekar (b. 1916)"
mkdir /tmp/"[DEBUG] Tulsakka Rohidekar (b. 1916) :: Vaman Rao Mirji (d. 1965) ⚭ Tulsakka Rohidekar (b. 1916)"
mkdir /tmp/"Narayana Rao Raghavendra Habbu (b. 1914, d. 1989) ⚭ Champakkabai Rohidekar (b. 1920, d. 1998)"
mkdir /tmp/"unique identifier: fde49ce4-4c9d-448f-a4b3-8d40237eeacf"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Narayana Rao Raghavendra Habbu (b. 1914, d. 1989) :: Narayana Rao Raghavendra Habbu (b. 1914, d. 1989) ⚭ Champakkabai Rohidekar (b. 1920, d. 1998)"
mkdir /tmp/"[DEBUG] Champakkabai Rohidekar (b. 1920, d. 1998) :: Narayana Rao Raghavendra Habbu (b. 1914, d. 1989) ⚭ Champakkabai Rohidekar (b. 1920, d. 1998)"
mkdir /tmp/"Ranga Rao Rohidekar (b. 1924) ⚭ Shankuntala Potdar"
mkdir /tmp/"unique identifier: 12651e36-5838-4912-872e-aec93aa03dbc"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Ranga Rao Rohidekar (b. 1924) :: Ranga Rao Rohidekar (b. 1924) ⚭ Shankuntala Potdar"
mkdir /tmp/"[DEBUG] Shankuntala Potdar :: Ranga Rao Rohidekar (b. 1924) ⚭ Shankuntala Potdar"
mkdir /tmp/"Vasant Rao Rohidekar (b. 1932) ⚭ Kaveri Parvatikar"
mkdir /tmp/"unique identifier: 55b2f290-c4fc-4121-8446-2a50e23ca87c"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Vasant Rao Rohidekar (b. 1932) :: Vasant Rao Rohidekar (b. 1932) ⚭ Kaveri Parvatikar"
mkdir /tmp/"[DEBUG] Kaveri Parvatikar :: Vasant Rao Rohidekar (b. 1932) ⚭ Kaveri Parvatikar"
mkdir /tmp/"Babu Rao Rohidekar (b. 1932) ⚭ Mirji/Shantabai Shantabai/"
mkdir /tmp/"unique identifier: b0dfe346-ded3-46d7-8dd9-85934616f644"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Babu Rao Rohidekar (b. 1932) :: Babu Rao Rohidekar (b. 1932) ⚭ Mirji/Shantabai Shantabai/"
mkdir /tmp/"[DEBUG] Mirji/Shantabai Shantabai/ :: Babu Rao Rohidekar (b. 1932) ⚭ Mirji/Shantabai Shantabai/"
mkdir /tmp/"Raghavendra (Raghu) Rohidekar (b. 1934) ⚭ Malati Kakmari"
mkdir /tmp/"unique identifier: e8989dd6-6020-425d-b6fb-ee30469992b9"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Raghavendra (Raghu) Rohidekar (b. 1934) :: Raghavendra (Raghu) Rohidekar (b. 1934) ⚭ Malati Kakmari"
mkdir /tmp/"[DEBUG] Malati Kakmari :: Raghavendra (Raghu) Rohidekar (b. 1934) ⚭ Malati Kakmari"
mkdir /tmp/"Bhimka Rao Rohidekar (d. 1920) ⚭ Radhabai"
mkdir /tmp/"unique identifier: 64133678-011e-4ca8-8a56-4eb89eb9040c"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Bhimka Rao Rohidekar (d. 1920) :: Bhimka Rao Rohidekar (d. 1920) ⚭ Radhabai"
mkdir /tmp/"[DEBUG] Radhabai :: Bhimka Rao Rohidekar (d. 1920) ⚭ Radhabai"
mkdir /tmp/"Raghavendra Jagirdar ⚭ Vatsala Rohidekar (b. 1928, d. 1953)"
mkdir /tmp/"unique identifier: ab8eacd5-1825-43d5-a2e7-f986002488fe"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Raghavendra Jagirdar :: Raghavendra Jagirdar ⚭ Vatsala Rohidekar (b. 1928, d. 1953)"
mkdir /tmp/"[DEBUG] Vatsala Rohidekar (b. 1928, d. 1953) :: Raghavendra Jagirdar ⚭ Vatsala Rohidekar (b. 1928, d. 1953)"
mkdir /tmp/"Sudhir Sarnobat (b. 1946) ⚭ Meenakshi Rohidekar (b. 1950)"
mkdir /tmp/"unique identifier: ac5cf235-02eb-4a25-b7bc-c8954cb0bda6"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Sudhir Sarnobat (b. 1946) :: Sudhir Sarnobat (b. 1946) ⚭ Meenakshi Rohidekar (b. 1950)"
mkdir /tmp/"[DEBUG] Meenakshi Rohidekar (b. 1950) :: Sudhir Sarnobat (b. 1946) ⚭ Meenakshi Rohidekar (b. 1950)"
mkdir /tmp/"Shamsundar Bengeri ⚭ Manjula Rohidekar"
mkdir /tmp/"unique identifier: 5ed81c8f-4006-43b5-a63b-9e840cb8477c"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Shamsundar Bengeri :: Shamsundar Bengeri ⚭ Manjula Rohidekar"
mkdir /tmp/"[DEBUG] Manjula Rohidekar :: Shamsundar Bengeri ⚭ Manjula Rohidekar"
mkdir /tmp/"Venkatesh Rohidekar ⚭ Latha Kulkarni"
mkdir /tmp/"unique identifier: b0f31bf7-e4b6-4c8e-8b7f-efc8b3576fa4"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Venkatesh Rohidekar :: Venkatesh Rohidekar ⚭ Latha Kulkarni"
mkdir /tmp/"[DEBUG] Latha Kulkarni :: Venkatesh Rohidekar ⚭ Latha Kulkarni"
mkdir /tmp/"Suresh Addabaddi ⚭ Vatsala/Vijaya Kshirsagar Kshirsagar/"
mkdir /tmp/"unique identifier: 6496c52d-f066-4f41-99c4-24cdb3944be5"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Suresh Addabaddi :: Suresh Addabaddi ⚭ Vatsala/Vijaya Kshirsagar Kshirsagar/"
mkdir /tmp/"[DEBUG] Vatsala/Vijaya Kshirsagar Kshirsagar/ :: Suresh Addabaddi ⚭ Vatsala/Vijaya Kshirsagar Kshirsagar/"
mkdir /tmp/"Surendra Muthalik ⚭ Sarala Addabaddi"
mkdir /tmp/"unique identifier: 4d1a3fee-6256-4197-95c0-6794716a3945"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Surendra Muthalik :: Surendra Muthalik ⚭ Sarala Addabaddi"
mkdir /tmp/"[DEBUG] Sarala Addabaddi :: Surendra Muthalik ⚭ Sarala Addabaddi"
mkdir /tmp/"Dattatreya Pujar ⚭ Jyothi Addabaddi"
mkdir /tmp/"unique identifier: 2003377f-59ce-4d96-a0d8-acde3cc15571"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Dattatreya Pujar :: Dattatreya Pujar ⚭ Jyothi Addabaddi"
mkdir /tmp/"[DEBUG] Jyothi Addabaddi :: Dattatreya Pujar ⚭ Jyothi Addabaddi"
mkdir /tmp/"Chakarapani Bangalore Krishnaswamny (d. 2009) ⚭ Puttaka Rohidekar"
mkdir /tmp/"unique identifier: 0e2c1d74-133e-45bd-9984-f8e27dfaee4f"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Chakarapani Bangalore Krishnaswamny (d. 2009) :: Chakarapani Bangalore Krishnaswamny (d. 2009) ⚭ Puttaka Rohidekar"
mkdir /tmp/"[DEBUG] Puttaka Rohidekar :: Chakarapani Bangalore Krishnaswamny (d. 2009) ⚭ Puttaka Rohidekar"
mkdir /tmp/"Narsimhamurthy DP ⚭ Lallakka Rohidekar"
mkdir /tmp/"unique identifier: fd5fb7b1-7589-41ba-8e80-694b5ad73d2e"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Narsimhamurthy DP :: Narsimhamurthy DP ⚭ Lallakka Rohidekar"
mkdir /tmp/"[DEBUG] Lallakka Rohidekar :: Narsimhamurthy DP ⚭ Lallakka Rohidekar"
mkdir /tmp/"Ranganath/Gopal Rohidekar Rohidekar/ ⚭ Radha"
mkdir /tmp/"unique identifier: 0e9160d8-06ab-41ac-8c6f-e49f7cf26f96"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Ranganath/Gopal Rohidekar Rohidekar/ :: Ranganath/Gopal Rohidekar Rohidekar/ ⚭ Radha"
mkdir /tmp/"[DEBUG] Radha :: Ranganath/Gopal Rohidekar Rohidekar/ ⚭ Radha"
mkdir /tmp/"Ashok Sadarjoshi ⚭ Nirmala/Asha Rohidekar Rohidekar/"
mkdir /tmp/"unique identifier: eef07e27-e8c1-4c5a-a254-c92247f629db"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Ashok Sadarjoshi :: Ashok Sadarjoshi ⚭ Nirmala/Asha Rohidekar Rohidekar/"
mkdir /tmp/"[DEBUG] Nirmala/Asha Rohidekar Rohidekar/ :: Ashok Sadarjoshi ⚭ Nirmala/Asha Rohidekar Rohidekar/"
mkdir /tmp/"Prakash Kulkarni ⚭ Prema Rohidekar"
mkdir /tmp/"unique identifier: 747c5db5-6fec-4da4-9990-dca3a8a27af4"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Prakash Kulkarni :: Prakash Kulkarni ⚭ Prema Rohidekar"
mkdir /tmp/"[DEBUG] Prema Rohidekar :: Prakash Kulkarni ⚭ Prema Rohidekar"
mkdir /tmp/"(no name) ⚭ Pushpa"
mkdir /tmp/"unique identifier: b7e38542-f1a6-44de-8ee1-43b34e6b12fa"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] (no name) :: (no name) ⚭ Pushpa"
mkdir /tmp/"[DEBUG] Pushpa :: (no name) ⚭ Pushpa"
mkdir /tmp/"Sridhar Rohidekar ⚭ Anjana"
mkdir /tmp/"unique identifier: 4d0a1b7f-c5bb-4137-86cc-ae0c610b1b60"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Sridhar Rohidekar :: Sridhar Rohidekar ⚭ Anjana"
mkdir /tmp/"[DEBUG] Anjana :: Sridhar Rohidekar ⚭ Anjana"
mkdir /tmp/"Gururaj Rohidekar ⚭ Manjula Benkai"
mkdir /tmp/"unique identifier: 2e9b519f-cb25-45e8-892e-2673c33f7107"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Gururaj Rohidekar :: Gururaj Rohidekar ⚭ Manjula Benkai"
mkdir /tmp/"[DEBUG] Manjula Benkai :: Gururaj Rohidekar ⚭ Manjula Benkai"
mkdir /tmp/"Vasant Nagsampige ⚭ Veena Rohidekar"
mkdir /tmp/"unique identifier: 6ccafd4b-64d5-4610-8c6a-433cfcaa41fd"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Vasant Nagsampige :: Vasant Nagsampige ⚭ Veena Rohidekar"
mkdir /tmp/"[DEBUG] Veena Rohidekar :: Vasant Nagsampige ⚭ Veena Rohidekar"
mkdir /tmp/"Venkatesh Rohidekar ⚭ Venkana"
mkdir /tmp/"unique identifier: 55bd570f-8aa6-4d9c-a673-2500353304d2"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Venkatesh Rohidekar :: Venkatesh Rohidekar ⚭ Venkana"
mkdir /tmp/"[DEBUG] Venkana :: Venkatesh Rohidekar ⚭ Venkana"
mkdir /tmp/"Govindaswamy ⚭ Rupa Rohidekar"
mkdir /tmp/"unique identifier: 0eb253ff-0293-4dd9-a2a5-656711781732"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Govindaswamy :: Govindaswamy ⚭ Rupa Rohidekar"
mkdir /tmp/"[DEBUG] Rupa Rohidekar :: Govindaswamy ⚭ Rupa Rohidekar"
mkdir /tmp/"Satish Rohidekar ⚭ Chitra Srinivasan"
mkdir /tmp/"unique identifier: 0ed3156f-8872-4c09-8fec-c45b63851389"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Satish Rohidekar :: Satish Rohidekar ⚭ Chitra Srinivasan"
mkdir /tmp/"[DEBUG] Chitra Srinivasan :: Satish Rohidekar ⚭ Chitra Srinivasan"
mkdir /tmp/"Krishnamurthy ⚭ Indumati Rohidekar"
mkdir /tmp/"unique identifier: 0763d7c5-73d8-4784-a7a0-027fe780ed2c"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Krishnamurthy :: Krishnamurthy ⚭ Indumati Rohidekar"
mkdir /tmp/"[DEBUG] Indumati Rohidekar :: Krishnamurthy ⚭ Indumati Rohidekar"
mkdir /tmp/"Krishnamurthy Rohidekar ⚭ Lakshmi"
mkdir /tmp/"unique identifier: 80daf538-5a3b-40aa-85fc-bc5037965dac"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Krishnamurthy Rohidekar :: Krishnamurthy Rohidekar ⚭ Lakshmi"
mkdir /tmp/"[DEBUG] Lakshmi :: Krishnamurthy Rohidekar ⚭ Lakshmi"
mkdir /tmp/"Narayan K (b. 1980) ⚭ Madhavi"
mkdir /tmp/"unique identifier: 30bfd659-57f8-4a30-ad40-adc04cd4c196"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Narayan K (b. 1980) :: Narayan K (b. 1980) ⚭ Madhavi"
mkdir /tmp/"[DEBUG] Madhavi :: Narayan K (b. 1980) ⚭ Madhavi"
mkdir /tmp/"Jeevan Bharadhwaj DN ⚭ Tejasvi N Rao"
mkdir /tmp/"unique identifier: 4b63054f-59c1-44fc-9ddc-e85948c5198d"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Jeevan Bharadhwaj DN :: Jeevan Bharadhwaj DN ⚭ Tejasvi N Rao"
mkdir /tmp/"[DEBUG] Tejasvi N Rao :: Jeevan Bharadhwaj DN ⚭ Tejasvi N Rao"
mkdir /tmp/"Yoga ⚭ Soudamini Gombi (b. 1984)"
mkdir /tmp/"unique identifier: ef3ca2d3-971e-43fd-b484-398c3e38c0fb"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Yoga :: Yoga ⚭ Soudamini Gombi (b. 1984)"
mkdir /tmp/"[DEBUG] Soudamini Gombi (b. 1984) :: Yoga ⚭ Soudamini Gombi (b. 1984)"
mkdir /tmp/"Gururaj Beloli ⚭ Archana Muthalik"
mkdir /tmp/"unique identifier: 9977ac7f-c54f-4d42-b67b-d7825d28bbc3"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Gururaj Beloli :: Gururaj Beloli ⚭ Archana Muthalik"
mkdir /tmp/"[DEBUG] Archana Muthalik :: Gururaj Beloli ⚭ Archana Muthalik"
mkdir /tmp/"Amit Umrani ⚭ Vandana Muthalik"
mkdir /tmp/"unique identifier: 9bd2c3ea-7262-456d-a0ee-bd513ab31c52"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Amit Umrani :: Amit Umrani ⚭ Vandana Muthalik"
mkdir /tmp/"[DEBUG] Vandana Muthalik :: Amit Umrani ⚭ Vandana Muthalik"
mkdir /tmp/"Vaman Rao (d. 2014) — Usha"
mkdir /tmp/"unique identifier: 5b00dba0-a59e-e3c3-26eb-997f70000280"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Vaman Rao (d. 2014) :: Vaman Rao (d. 2014) — Usha"
mkdir /tmp/"[DEBUG] Usha :: Vaman Rao (d. 2014) — Usha"
mkdir /tmp/"Sudharshan Harihar — Suma Sudharshan"
mkdir /tmp/"unique identifier: 5b00dba0-a57a-63c2-e6eb-997f70000280"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Sudharshan Harihar :: Sudharshan Harihar — Suma Sudharshan"
mkdir /tmp/"[DEBUG] Suma Sudharshan :: Sudharshan Harihar — Suma Sudharshan"
mkdir /tmp/"Shreeneedhi DN — Rashmi"
mkdir /tmp/"unique identifier: bde90e43-c6dc-4187-8f86-24f810b08921"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Shreeneedhi DN :: Shreeneedhi DN — Rashmi"
mkdir /tmp/"[DEBUG] Rashmi :: Shreeneedhi DN — Rashmi"
mkdir /tmp/"Rajiva Rohidekar — Amruta"
mkdir /tmp/"unique identifier: 0fedbf33-8812-4805-a74f-da4e52037d5f"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Rajiva Rohidekar :: Rajiva Rohidekar — Amruta"
mkdir /tmp/"[DEBUG] Amruta :: Rajiva Rohidekar — Amruta"
mkdir /tmp/"Jayaraj Rohidekar — Vijaya Sadarjoshi"
mkdir /tmp/"unique identifier: ed066906-bfc4-45a2-98d1-5422032e28e9"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Jayaraj Rohidekar :: Jayaraj Rohidekar — Vijaya Sadarjoshi"
mkdir /tmp/"[DEBUG] Vijaya Sadarjoshi :: Jayaraj Rohidekar — Vijaya Sadarjoshi"
mkdir /tmp/"Jagdish — Megha Bengeri"
mkdir /tmp/"unique identifier: 5b00dba0-a617-43c4-46eb-997f70000280"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Jagdish :: Jagdish — Megha Bengeri"
mkdir /tmp/"[DEBUG] Megha Bengeri :: Jagdish — Megha Bengeri"
mkdir /tmp/"Amit Bengeri — Varada"
mkdir /tmp/"unique identifier: d55cb6c8-5835-49a9-9169-b6be5591ec02"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Amit Bengeri :: Amit Bengeri — Varada"
mkdir /tmp/"[DEBUG] Varada :: Amit Bengeri — Varada"
mkdir /tmp/"Durgaprasad Bilagi — Bhavana Rohidekar (b. 1989)"
mkdir /tmp/"unique identifier: 5b00dba0-a63c-53c4-a6eb-997f70000280"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Durgaprasad Bilagi :: Durgaprasad Bilagi — Bhavana Rohidekar (b. 1989)"
mkdir /tmp/"[DEBUG] Bhavana Rohidekar (b. 1989) :: Durgaprasad Bilagi — Bhavana Rohidekar (b. 1989)"
mkdir /tmp/"Sagar Addabaddi (b. 1980) — (no name)"
mkdir /tmp/"unique identifier: cc635a07-f36b-461b-861a-72f5a7ad789c"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Sagar Addabaddi (b. 1980) :: Sagar Addabaddi (b. 1980) — (no name)"
mkdir /tmp/"[DEBUG] (no name) :: Sagar Addabaddi (b. 1980) — (no name)"
mkdir /tmp/"Raghavendra Rao S — Sulabha/Shuba Rao Addabaddi Addabaddi/"
mkdir /tmp/"unique identifier: 5b00dba0-a692-43c5-26eb-997f70000280"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Raghavendra Rao S :: Raghavendra Rao S — Sulabha/Shuba Rao Addabaddi Addabaddi/"
mkdir /tmp/"[DEBUG] Sulabha/Shuba Rao Addabaddi Addabaddi/ :: Raghavendra Rao S — Sulabha/Shuba Rao Addabaddi Addabaddi/"
mkdir /tmp/"(no name) — Anagha Pujar"
mkdir /tmp/"unique identifier: 5b00dba0-a6e2-73c5-96eb-997f70000280"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] (no name) :: (no name) — Anagha Pujar"
mkdir /tmp/"[DEBUG] Anagha Pujar :: (no name) — Anagha Pujar"
mkdir /tmp/"Vishal Pujar — (no name)"
mkdir /tmp/"unique identifier: 51088a91-022b-429c-aaf9-7d5ae0c56298"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Vishal Pujar :: Vishal Pujar — (no name)"
mkdir /tmp/"[DEBUG] (no name) :: Vishal Pujar — (no name)"
mkdir /tmp/"K Harish — Vasanthi ‘Bhagi’ Harish"
mkdir /tmp/"unique identifier: 5b00dba0-a753-43c6-16eb-997f70000280"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] K Harish :: K Harish — Vasanthi ‘Bhagi’ Harish"
mkdir /tmp/"[DEBUG] Vasanthi ‘Bhagi’ Harish :: K Harish — Vasanthi ‘Bhagi’ Harish"
mkdir /tmp/"Appu — (no name)"
mkdir /tmp/"unique identifier: 5b00dba0-a7ae-f3c6-66eb-997f70000280"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Appu :: Appu — (no name)"
mkdir /tmp/"[DEBUG] (no name) :: Appu — (no name)"
mkdir /tmp/"Dr M V Mahishi — Jinki Prema"
mkdir /tmp/"unique identifier: 5b00dba0-a805-c3c6-d6eb-997f70000280"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Dr M V Mahishi :: Dr M V Mahishi — Jinki Prema"
mkdir /tmp/"[DEBUG] Jinki Prema :: Dr M V Mahishi — Jinki Prema"
mkdir /tmp/"Vinayak Desai — Snehalata / Appu Appu / Appu //"
mkdir /tmp/"unique identifier: 5b00dba0-a8a3-63c7-d6eb-997f70000280"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Vinayak Desai :: Vinayak Desai — Snehalata / Appu Appu / Appu //"
mkdir /tmp/"[DEBUG] Snehalata / Appu Appu / Appu // :: Vinayak Desai — Snehalata / Appu Appu / Appu //"
mkdir /tmp/"Gururajachav — Sudha/'Baby' 'Baby' 'Baby'/"
mkdir /tmp/"unique identifier: 5b00dba0-a8b0-f3c7-f6eb-997f70000280"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Gururajachav :: Gururajachav — Sudha/'Baby' 'Baby' 'Baby'/"
mkdir /tmp/"[DEBUG] Sudha/'Baby' 'Baby' 'Baby'/ :: Gururajachav — Sudha/'Baby' 'Baby' 'Baby'/"
mkdir /tmp/"Shashidar Kulkarni — Archana Kulkarni"
mkdir /tmp/"unique identifier: 5b00dba0-a8d3-83c8-46eb-997f70000280"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Shashidar Kulkarni :: Shashidar Kulkarni — Archana Kulkarni"
mkdir /tmp/"[DEBUG] Archana Kulkarni :: Shashidar Kulkarni — Archana Kulkarni"
mkdir /tmp/"Pralad Rao Wai — Vijaya / Viji Viji / Viji //"
mkdir /tmp/"unique identifier: 5b00dba0-a901-93c8-b6eb-997f70000280"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Pralad Rao Wai :: Pralad Rao Wai — Vijaya / Viji Viji / Viji //"
mkdir /tmp/"[DEBUG] Vijaya / Viji Viji / Viji // :: Pralad Rao Wai — Vijaya / Viji Viji / Viji //"
mkdir /tmp/"Uday Savadatti — Anuraddha Rohidekar"
mkdir /tmp/"unique identifier: 5b00dba0-a967-83c9-a6eb-997f70000280"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Uday Savadatti :: Uday Savadatti — Anuraddha Rohidekar"
mkdir /tmp/"[DEBUG] Anuraddha Rohidekar :: Uday Savadatti — Anuraddha Rohidekar"
mkdir /tmp/"Giridhar Deshpande — Rohini Rohidekar"
mkdir /tmp/"unique identifier: 5b00dba0-a97a-b3c9-d6eb-997f70000280"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Giridhar Deshpande :: Giridhar Deshpande — Rohini Rohidekar"
mkdir /tmp/"[DEBUG] Rohini Rohidekar :: Giridhar Deshpande — Rohini Rohidekar"
mkdir /tmp/"Shree Rohidekar — Girish Dixit"
mkdir /tmp/"unique identifier: b7708550-baa9-42a5-b69c-ca581f45b51b"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Shree Rohidekar :: Shree Rohidekar — Girish Dixit"
mkdir /tmp/"[DEBUG] Girish Dixit :: Shree Rohidekar — Girish Dixit"
mkdir /tmp/"Raghavendra — Rashmi Govind (b. 1985)"
mkdir /tmp/"unique identifier: 5b00dba0-a9d5-f3ca-a6eb-997f70000280"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Raghavendra :: Raghavendra — Rashmi Govind (b. 1985)"
mkdir /tmp/"[DEBUG] Rashmi Govind (b. 1985) :: Raghavendra — Rashmi Govind (b. 1985)"
mkdir /tmp/"Hariprasad — Ramya Govind (b. 1988)"
mkdir /tmp/"unique identifier: 5b00dba0-a9fb-e3ca-f6eb-997f70000280"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Hariprasad :: Hariprasad — Ramya Govind (b. 1988)"
mkdir /tmp/"[DEBUG] Ramya Govind (b. 1988) :: Hariprasad — Ramya Govind (b. 1988)"
mkdir /tmp/"Minaz Sajan — Meghana Simha (b. 14 Aug 1984)"
mkdir /tmp/"unique identifier: 5b00dba0-aa19-d3cb-26eb-997f70000280"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Minaz Sajan :: Minaz Sajan — Meghana Simha (b. 14 Aug 1984)"
mkdir /tmp/"[DEBUG] Meghana Simha (b. 14 Aug 1984) :: Minaz Sajan — Meghana Simha (b. 14 Aug 1984)"
mkdir /tmp/"Ramesh R Habbu (d. 2000) — (no name)"
mkdir /tmp/"unique identifier: 55b4fa52-939e-4f15-af11-3f2c06e33122"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Ramesh R Habbu (d. 2000) :: Ramesh R Habbu (d. 2000) — (no name)"
mkdir /tmp/"[DEBUG] (no name) :: Ramesh R Habbu (d. 2000) — (no name)"
mkdir /tmp/"Ravindra / Anil? Anil? / Anil? // (d. 2010) ⚭ Dr Rajini"
mkdir /tmp/"unique identifier: 5b00dba0-a834-b3c7-16eb-997f70000280"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Ravindra / Anil? Anil? / Anil? // (d. 2010) :: Ravindra / Anil? Anil? / Anil? // (d. 2010) ⚭ Dr Rajini"
mkdir /tmp/"[DEBUG] Dr Rajini :: Ravindra / Anil? Anil? / Anil? // (d. 2010) ⚭ Dr Rajini"
mkdir /tmp/"Ramesh ⚭ Leela"
mkdir /tmp/"unique identifier: 5fddb131-39f6-42ec-8734-96af6df8a579"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Ramesh :: Ramesh ⚭ Leela"
mkdir /tmp/"[DEBUG] Leela :: Ramesh ⚭ Leela"
mkdir /tmp/"Dr Anand Rao ⚭ Dr Prathibha"
mkdir /tmp/"unique identifier: 5b00dba0-a915-23c8-e6eb-997f70000280"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Dr Anand Rao :: Dr Anand Rao ⚭ Dr Prathibha"
mkdir /tmp/"[DEBUG] Dr Prathibha :: Dr Anand Rao ⚭ Dr Prathibha"
mkdir /tmp/"Prakash ⚭ (no name)"
mkdir /tmp/"unique identifier: 5b00dba0-a922-83c9-06eb-997f70000280"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Prakash :: Prakash ⚭ (no name)"
mkdir /tmp/"[DEBUG] (no name) :: Prakash ⚭ (no name)"
mkdir /tmp/"Joshua Vallis ⚭ Priya Sarnobat (b. 1989)"
mkdir /tmp/"unique identifier: 5e6e897d-b9e0-2598-ffff-fb8e3a138280"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Joshua Vallis :: Joshua Vallis ⚭ Priya Sarnobat (b. 1989)"
mkdir /tmp/"[DEBUG] Priya Sarnobat (b. 1989) :: Joshua Vallis ⚭ Priya Sarnobat (b. 1989)"
mkdir /tmp/"Vibhas Rohidekar (b. 1985) ⚭ (no name)"
mkdir /tmp/"unique identifier: 48cdd238-da3a-4b76-853b-6803398e5a5e"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Vibhas Rohidekar (b. 1985) :: Vibhas Rohidekar (b. 1985) ⚭ (no name)"
mkdir /tmp/"[DEBUG] (no name) :: Vibhas Rohidekar (b. 1985) ⚭ (no name)"
mkdir /tmp/"Madan ⚭ Ashwini Rohidekar (b. 7 Apr 1996)"
mkdir /tmp/"unique identifier: 5e6e8edb-dc19-a6c6-6584-d8f0e0000410"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Madan :: Madan ⚭ Ashwini Rohidekar (b. 7 Apr 1996)"
mkdir /tmp/"[DEBUG] Ashwini Rohidekar (b. 7 Apr 1996) :: Madan ⚭ Ashwini Rohidekar (b. 7 Apr 1996)"
mkdir /tmp/"Suhas Harihar ⚭ Ritinder Kaur"
mkdir /tmp/"unique identifier: 5e6e8f2e-8d52-86c7-0584-d8f0e0000410"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Suhas Harihar :: Suhas Harihar ⚭ Ritinder Kaur"
mkdir /tmp/"[DEBUG] Ritinder Kaur :: Suhas Harihar ⚭ Ritinder Kaur"
mkdir /tmp/"Rahul Rohidekar ⚭ Rashmi"
mkdir /tmp/"unique identifier: dd177dbe-9db0-4a08-80e7-13d195681ab2"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Rahul Rohidekar :: Rahul Rohidekar ⚭ Rashmi"
mkdir /tmp/"[DEBUG] Rashmi :: Rahul Rohidekar ⚭ Rashmi"
mkdir /tmp/"Darshan Gogga ⚭ Sindu Gombi (b. 1991)"
mkdir /tmp/"unique identifier: 603befec-ccff-91eb-2389-000000000000"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Darshan Gogga :: Darshan Gogga ⚭ Sindu Gombi (b. 1991)"
mkdir /tmp/"[DEBUG] Sindu Gombi (b. 1991) :: Darshan Gogga ⚭ Sindu Gombi (b. 1991)"
mkdir /tmp/"Dilip Krishnamurthy (b. 1990) ⚭ Dhruti Ramya (b. 1995)"
mkdir /tmp/"unique identifier: 6f0bab2d-f3d3-488d-bedb-3c790f2734fa"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Dilip Krishnamurthy (b. 1990) :: Dilip Krishnamurthy (b. 1990) ⚭ Dhruti Ramya (b. 1995)"
mkdir /tmp/"[DEBUG] Dhruti Ramya (b. 1995) :: Dilip Krishnamurthy (b. 1990) ⚭ Dhruti Ramya (b. 1995)"
mkdir /tmp/"Panchamukhi ⚭ Geeta Rohidekar"
mkdir /tmp/"unique identifier: 603bf301-ccff-91eb-2389-000000000000"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Panchamukhi :: Panchamukhi ⚭ Geeta Rohidekar"
mkdir /tmp/"[DEBUG] Geeta Rohidekar :: Panchamukhi ⚭ Geeta Rohidekar"
mkdir /tmp/"Arun Bellubbi ⚭ Nalini Rohidekar"
mkdir /tmp/"unique identifier: 603bf377-ccff-91eb-2389-000000000000"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Arun Bellubbi :: Arun Bellubbi ⚭ Nalini Rohidekar"
mkdir /tmp/"[DEBUG] Nalini Rohidekar :: Arun Bellubbi ⚭ Nalini Rohidekar"
mkdir /tmp/"Sreenivas Rohidekar ⚭ Sunita"
mkdir /tmp/"unique identifier: f16273d9-75e0-424e-8b24-dba10a33921c"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Sreenivas Rohidekar :: Sreenivas Rohidekar ⚭ Sunita"
mkdir /tmp/"[DEBUG] Sunita :: Sreenivas Rohidekar ⚭ Sunita"
mkdir /tmp/"Vineeth (b. 1982) ⚭ Tejashree Simha (b. 1 Mar 1989)"
mkdir /tmp/"unique identifier: 603c08de-ccff-91eb-2389-000000000000"
mkdir /tmp/""
mkdir /tmp/"[DEBUG] Vineeth (b. 1982) :: Vineeth (b. 1982) ⚭ Tejashree Simha (b. 1 Mar 1989)"
mkdir /tmp/"[DEBUG] Tejashree Simha (b. 1 Mar 1989) :: Vineeth (b. 1982) ⚭ Tejashree Simha (b. 1 Mar 1989)"
mkdir /tmp/""
mkdir /tmp/"/Laxman Rao Rohidekar (b. 1847, d. 1934)"
mkdir /tmp/"/Anand Rao Rohidekar (d. 1895)"
mkdir /tmp/"/Bhimka Rao Rohidekar (d. 1920)"
mkdir /tmp/"/Venkawwa Rohidekar"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Venkatesh Rohidekar (b. 1889, d. 1906)  (-- Rangubai Padki)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Ramachandra Rao Rohidekar (b. 1912, d. 1984)  (-- Sitabai Anikhindi)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Ramachandra Rao Rohidekar (b. 1912, d. 1984)  (-- Sitabai Anikhindi)/Puttaka Rohidekar  (-- Chakarapani Bangalore Krishnaswamny)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Ramachandra Rao Rohidekar (b. 1912, d. 1984)  (-- Sitabai Anikhindi)/Puttaka Rohidekar  (-- Chakarapani Bangalore Krishnaswamny)/Madhavi  (-- Narayan K)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Ramachandra Rao Rohidekar (b. 1912, d. 1984)  (-- Sitabai Anikhindi)/Lallakka Rohidekar  (-- Narsimhamurthy DP)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Ramachandra Rao Rohidekar (b. 1912, d. 1984)  (-- Sitabai Anikhindi)/Lallakka Rohidekar  (-- Narsimhamurthy DP)/Jeevan Bharadhwaj DN  (-- Tejasvi N Rao)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Ramachandra Rao Rohidekar (b. 1912, d. 1984)  (-- Sitabai Anikhindi)/Lallakka Rohidekar  (-- Narsimhamurthy DP)/Jeevan Bharadhwaj DN  (-- Tejasvi N Rao)/Bharadhwaj DN"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Ramachandra Rao Rohidekar (b. 1912, d. 1984)  (-- Sitabai Anikhindi)/Lallakka Rohidekar  (-- Narsimhamurthy DP)/Jeevan Bharadhwaj DN  (-- Tejasvi N Rao)/Bharadhwaj DN"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Ramachandra Rao Rohidekar (b. 1912, d. 1984)  (-- Sitabai Anikhindi)/Lallakka Rohidekar  (-- Narsimhamurthy DP)/Pujitha Nagarajan"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Ramachandra Rao Rohidekar (b. 1912, d. 1984)  (-- Sitabai Anikhindi)/Lallakka Rohidekar  (-- Narsimhamurthy DP)/Shreeneedhi DN  (-- Rashmi)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Ramachandra Rao Rohidekar (b. 1912, d. 1984)  (-- Sitabai Anikhindi)/Lallakka Rohidekar  (-- Narsimhamurthy DP)/Shreeneedhi DN  (-- Rashmi)/Sanvi"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Ramachandra Rao Rohidekar (b. 1912, d. 1984)  (-- Sitabai Anikhindi)/Ranganath/Gopal Rohidekar Rohidekar/  (-- Radha)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Ramachandra Rao Rohidekar (b. 1912, d. 1984)  (-- Sitabai Anikhindi)/Ranganath/Gopal Rohidekar Rohidekar/  (-- Radha)/Rajiva Rohidekar  (-- Amruta)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Ramachandra Rao Rohidekar (b. 1912, d. 1984)  (-- Sitabai Anikhindi)/Ranganath/Gopal Rohidekar Rohidekar/  (-- Radha)/Rajiva Rohidekar  (-- Amruta)/Rohidekar"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Ramachandra Rao Rohidekar (b. 1912, d. 1984)  (-- Sitabai Anikhindi)/Ranganath/Gopal Rohidekar Rohidekar/  (-- Radha)/Rahul Rohidekar  (-- Rashmi)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Ramachandra Rao Rohidekar (b. 1912, d. 1984)  (-- Sitabai Anikhindi)/Ranganath/Gopal Rohidekar Rohidekar/  (-- Radha)/Rahul Rohidekar  (-- Rashmi)/Rohidekar (b. 17 Feb 2021)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Ramachandra Rao Rohidekar (b. 1912, d. 1984)  (-- Sitabai Anikhindi)/Nirmala/Asha Rohidekar Rohidekar/  (-- Ashok Sadarjoshi)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Ramachandra Rao Rohidekar (b. 1912, d. 1984)  (-- Sitabai Anikhindi)/Jayaraj Rohidekar  (-- Vijaya Sadarjoshi)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Ramachandra Rao Rohidekar (b. 1912, d. 1984)  (-- Sitabai Anikhindi)/Jayaraj Rohidekar  (-- Vijaya Sadarjoshi)/Ajay Rohidekar"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Ramachandra Rao Rohidekar (b. 1912, d. 1984)  (-- Sitabai Anikhindi)/Prema Rohidekar  (-- Prakash Kulkarni)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Ramachandra Rao Rohidekar (b. 1912, d. 1984)  (-- Sitabai Anikhindi)/Prema Rohidekar  (-- Prakash Kulkarni)/Prasanna Kulkarni"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Ramachandra Rao Rohidekar (b. 1912, d. 1984)  (-- Sitabai Anikhindi)/Prema Rohidekar  (-- Prakash Kulkarni)/Poornima Kulkarni"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Shamaji Rao Rohidekar (b. 15 Sep 1915)  (-- Laxmibai Rama)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Shamaji Rao Rohidekar (b. 15 Sep 1915)  (-- Laxmibai Rama)/Ravindra Rohidekar (b. 1947, d. 2000)  (-- Snehalata Rao)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Shamaji Rao Rohidekar (b. 15 Sep 1915)  (-- Laxmibai Rama)/Ravindra Rohidekar (b. 1947, d. 2000)  (-- Snehalata Rao)/Gautham Rohidekar (b. 1975)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Shamaji Rao Rohidekar (b. 15 Sep 1915)  (-- Laxmibai Rama)/Ravindra Rohidekar (b. 1947, d. 2000)  (-- Snehalata Rao)/Puneet Rohidekar (b. 1981)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Shamaji Rao Rohidekar (b. 15 Sep 1915)  (-- Laxmibai Rama)/Meenakshi Rohidekar (b. 1950)  (-- Sudhir Sarnobat)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Shamaji Rao Rohidekar (b. 15 Sep 1915)  (-- Laxmibai Rama)/Meenakshi Rohidekar (b. 1950)  (-- Sudhir Sarnobat)/Prakash Sarnobat (b. 1978)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Shamaji Rao Rohidekar (b. 15 Sep 1915)  (-- Laxmibai Rama)/Meenakshi Rohidekar (b. 1950)  (-- Sudhir Sarnobat)/Sridhar Sarnobat (b. 1982)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Shamaji Rao Rohidekar (b. 15 Sep 1915)  (-- Laxmibai Rama)/Meenakshi Rohidekar (b. 1950)  (-- Sudhir Sarnobat)/Priya Sarnobat (b. 1989)  (-- Joshua Vallis)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Shamaji Rao Rohidekar (b. 15 Sep 1915)  (-- Laxmibai Rama)/Meenakshi Rohidekar (b. 1950)  (-- Sudhir Sarnobat)/Priya Sarnobat (b. 1989)  (-- Joshua Vallis)/Jaguar Vallis"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Shamaji Rao Rohidekar (b. 15 Sep 1915)  (-- Laxmibai Rama)/Deepak Rohidekar (b. 1964)  (-- Anupama)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Shamaji Rao Rohidekar (b. 15 Sep 1915)  (-- Laxmibai Rama)/Deepak Rohidekar (b. 1964)  (-- Anupama)/Gaurav Rohidekar"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Shamaji Rao Rohidekar (b. 15 Sep 1915)  (-- Laxmibai Rama)/Srinivas Rohidekar"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Shamaji Rao Rohidekar (b. 15 Sep 1915)  (-- Laxmibai Rama)/(stillborn) Rohidekar"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Bhagavanth Rao Rohidekar (b. Bet. 5 and 1918)  (-- Krishna/Shantabai Talikoti Talikoti/)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Bhagavanth Rao Rohidekar (b. Bet. 5 and 1918)  (-- Krishna/Shantabai Talikoti Talikoti/)/Manjula Rohidekar  (-- Shamsundar Bengeri)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Bhagavanth Rao Rohidekar (b. Bet. 5 and 1918)  (-- Krishna/Shantabai Talikoti Talikoti/)/Manjula Rohidekar  (-- Shamsundar Bengeri)/Megha Bengeri  (-- Jagdish)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Bhagavanth Rao Rohidekar (b. Bet. 5 and 1918)  (-- Krishna/Shantabai Talikoti Talikoti/)/Manjula Rohidekar  (-- Shamsundar Bengeri)/Megha Bengeri  (-- Jagdish)/(no name)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Bhagavanth Rao Rohidekar (b. Bet. 5 and 1918)  (-- Krishna/Shantabai Talikoti Talikoti/)/Manjula Rohidekar  (-- Shamsundar Bengeri)/Amit Bengeri  (-- Varada)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Bhagavanth Rao Rohidekar (b. Bet. 5 and 1918)  (-- Krishna/Shantabai Talikoti Talikoti/)/Manjula Rohidekar  (-- Shamsundar Bengeri)/Amit Bengeri  (-- Varada)/Bengeri"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Bhagavanth Rao Rohidekar (b. Bet. 5 and 1918)  (-- Krishna/Shantabai Talikoti Talikoti/)/Parimala Rohidekar  (-- Sham Gombi)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Bhagavanth Rao Rohidekar (b. Bet. 5 and 1918)  (-- Krishna/Shantabai Talikoti Talikoti/)/Parimala Rohidekar  (-- Sham Gombi)/Soudamini Gombi (b. 1984)  (-- Yoga)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Bhagavanth Rao Rohidekar (b. Bet. 5 and 1918)  (-- Krishna/Shantabai Talikoti Talikoti/)/Parimala Rohidekar  (-- Sham Gombi)/Soudamini Gombi (b. 1984)  (-- Yoga)/Kush"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Bhagavanth Rao Rohidekar (b. Bet. 5 and 1918)  (-- Krishna/Shantabai Talikoti Talikoti/)/Parimala Rohidekar  (-- Sham Gombi)/Sindu Gombi (b. 1991)  (-- Darshan Gogga)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Bhagavanth Rao Rohidekar (b. Bet. 5 and 1918)  (-- Krishna/Shantabai Talikoti Talikoti/)/Anand Rohidekar  (-- Vidya Rao)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Bhagavanth Rao Rohidekar (b. Bet. 5 and 1918)  (-- Krishna/Shantabai Talikoti Talikoti/)/Anand Rohidekar  (-- Vidya Rao)/Bhavana Rohidekar (b. 1989)  (-- Durgaprasad Bilagi)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Bhagavanth Rao Rohidekar (b. Bet. 5 and 1918)  (-- Krishna/Shantabai Talikoti Talikoti/)/Anand Rohidekar  (-- Vidya Rao)/Bhavana Rohidekar (b. 1989)  (-- Durgaprasad Bilagi)/Swaraat Bilagi"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Bhagavanth Rao Rohidekar (b. Bet. 5 and 1918)  (-- Krishna/Shantabai Talikoti Talikoti/)/Anand Rohidekar  (-- Vidya Rao)/Bhavana Rohidekar (b. 1989)  (-- Durgaprasad Bilagi)/Bilagi (b. 20 Feb 2021)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Bhagavanth Rao Rohidekar (b. Bet. 5 and 1918)  (-- Krishna/Shantabai Talikoti Talikoti/)/Venkatesh Rohidekar  (-- Latha Kulkarni)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Bhagavanth Rao Rohidekar (b. Bet. 5 and 1918)  (-- Krishna/Shantabai Talikoti Talikoti/)/Madhav Rohidekar"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (b. 21 Aug 1921, d. 9 Feb 2000)  (-- Sumitra/Geetabai Dani Dani/)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (b. 21 Aug 1921, d. 9 Feb 2000)  (-- Sumitra/Geetabai Dani Dani/)/Vidya Rohidekar (b. 28 Sep 10)  (-- Vaman Simha)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (b. 21 Aug 1921, d. 9 Feb 2000)  (-- Sumitra/Geetabai Dani Dani/)/Vidya Rohidekar (b. 28 Sep 10)  (-- Vaman Simha)/Meghana Simha (b. 14 Aug 1984)  (-- Minaz Sajan)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (b. 21 Aug 1921, d. 9 Feb 2000)  (-- Sumitra/Geetabai Dani Dani/)/Vidya Rohidekar (b. 28 Sep 10)  (-- Vaman Simha)/Meghana Simha (b. 14 Aug 1984)  (-- Minaz Sajan)/Sahir"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (b. 21 Aug 1921, d. 9 Feb 2000)  (-- Sumitra/Geetabai Dani Dani/)/Vidya Rohidekar (b. 28 Sep 10)  (-- Vaman Simha)/Meghana Simha (b. 14 Aug 1984)  (-- Minaz Sajan)/Mishka Sajan"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (b. 21 Aug 1921, d. 9 Feb 2000)  (-- Sumitra/Geetabai Dani Dani/)/Vidya Rohidekar (b. 28 Sep 10)  (-- Vaman Simha)/Tejashree Simha (b. 1 Mar 1989)  (-- Vineeth)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (b. 21 Aug 1921, d. 9 Feb 2000)  (-- Sumitra/Geetabai Dani Dani/)/Vinod Rohidekar (b. 19 Apr 57)  (-- Vasudha Kadiyali)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (b. 21 Aug 1921, d. 9 Feb 2000)  (-- Sumitra/Geetabai Dani Dani/)/Vinod Rohidekar (b. 19 Apr 57)  (-- Vasudha Kadiyali)/Vibhas Rohidekar (b. 1985)  (-- )"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (b. 21 Aug 1921, d. 9 Feb 2000)  (-- Sumitra/Geetabai Dani Dani/)/Vinod Rohidekar (b. 19 Apr 57)  (-- Vasudha Kadiyali)/Vandita Rohidekar (b. 1992)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (b. 21 Aug 1921, d. 9 Feb 2000)  (-- Sumitra/Geetabai Dani Dani/)/Vilas Rohidekar (b. 2 Feb 1961)  (-- Usha S. G)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (b. 21 Aug 1921, d. 9 Feb 2000)  (-- Sumitra/Geetabai Dani Dani/)/Veena Rohidekar (b. 4 May 1964)  (-- Jayaprakash Veena Jayaprakash)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (b. 21 Aug 1921, d. 9 Feb 2000)  (-- Sumitra/Geetabai Dani Dani/)/Veena Rohidekar (b. 4 May 1964)  (-- Jayaprakash Veena Jayaprakash)/Ketaki Jayaprakash (b. 1997)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (b. 21 Aug 1921, d. 9 Feb 2000)  (-- Sumitra/Geetabai Dani Dani/)/Vijay Rohidekar (b. 2 Feb 1966)  (-- Anuradha Kulkarni)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (b. 21 Aug 1921, d. 9 Feb 2000)  (-- Sumitra/Geetabai Dani Dani/)/Vijay Rohidekar (b. 2 Feb 1966)  (-- Anuradha Kulkarni)/Poorvi Rohidekar (b. 21 Oct 1998)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (b. 21 Aug 1921, d. 9 Feb 2000)  (-- Sumitra/Geetabai Dani Dani/)/Vijay Rohidekar (b. 2 Feb 1966)  (-- Anuradha Kulkarni)/Varsha Rohidekar (b. 6 Jul 2003)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (b. 21 Aug 1921, d. 9 Feb 2000)  (-- Sumitra/Geetabai Dani Dani/)/Vasanthi Rohidekar (b. 15 Feb 1970)  (-- Vasudevan)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (b. 21 Aug 1921, d. 9 Feb 2000)  (-- Sumitra/Geetabai Dani Dani/)/Vasanthi Rohidekar (b. 15 Feb 1970)  (-- Vasudevan)/Vallabh Vasudevan"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (b. 21 Aug 1921, d. 9 Feb 2000)  (-- Sumitra/Geetabai Dani Dani/)/Vasanthi Rohidekar (b. 15 Feb 1970)  (-- Vasudevan)/Vaibhav Vasudevan"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (b. 21 Aug 1921, d. 9 Feb 2000)  (-- Sumitra/Geetabai Dani Dani/)/Rohidekar (d. 1963)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Srinivas Rohidekar (b. 1923, d. 1930)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Godavari Rohidekar (b. 1925, d. 1980)  (-- Muralidhar Addabaddi)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Godavari Rohidekar (b. 1925, d. 1980)  (-- Muralidhar Addabaddi)/Suresh Addabaddi  (-- Vatsala/Vijaya Kshirsagar Kshirsagar/)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Godavari Rohidekar (b. 1925, d. 1980)  (-- Muralidhar Addabaddi)/Suresh Addabaddi  (-- Vatsala/Vijaya Kshirsagar Kshirsagar/)/Sandeep ('Peetu') Addabaddi"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Godavari Rohidekar (b. 1925, d. 1980)  (-- Muralidhar Addabaddi)/Suresh Addabaddi  (-- Vatsala/Vijaya Kshirsagar Kshirsagar/)/Sagar Addabaddi (b. 1980)  (-- )"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Godavari Rohidekar (b. 1925, d. 1980)  (-- Muralidhar Addabaddi)/Suresh Addabaddi  (-- Vatsala/Vijaya Kshirsagar Kshirsagar/)/Sagar Addabaddi (b. 1980)  (-- )/Addabaddi"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Godavari Rohidekar (b. 1925, d. 1980)  (-- Muralidhar Addabaddi)/Suresh Addabaddi  (-- Vatsala/Vijaya Kshirsagar Kshirsagar/)/Sagar Addabaddi (b. 1980)  (-- )/Addabaddi"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Godavari Rohidekar (b. 1925, d. 1980)  (-- Muralidhar Addabaddi)/Sulabha/Shuba Rao Addabaddi Addabaddi/  (-- Raghavendra Rao S)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Godavari Rohidekar (b. 1925, d. 1980)  (-- Muralidhar Addabaddi)/Sarala Addabaddi  (-- Surendra Muthalik)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Godavari Rohidekar (b. 1925, d. 1980)  (-- Muralidhar Addabaddi)/Sarala Addabaddi  (-- Surendra Muthalik)/Archana Muthalik  (-- Gururaj Beloli)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Godavari Rohidekar (b. 1925, d. 1980)  (-- Muralidhar Addabaddi)/Sarala Addabaddi  (-- Surendra Muthalik)/Archana Muthalik  (-- Gururaj Beloli)/Beloli"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Godavari Rohidekar (b. 1925, d. 1980)  (-- Muralidhar Addabaddi)/Sarala Addabaddi  (-- Surendra Muthalik)/Archana Muthalik  (-- Gururaj Beloli)/Beloli"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Godavari Rohidekar (b. 1925, d. 1980)  (-- Muralidhar Addabaddi)/Sarala Addabaddi  (-- Surendra Muthalik)/Vandana Muthalik  (-- Amit Umrani)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Godavari Rohidekar (b. 1925, d. 1980)  (-- Muralidhar Addabaddi)/Sarala Addabaddi  (-- Surendra Muthalik)/Meghana Muthalik"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Godavari Rohidekar (b. 1925, d. 1980)  (-- Muralidhar Addabaddi)/Jyothi Addabaddi  (-- Dattatreya Pujar)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Godavari Rohidekar (b. 1925, d. 1980)  (-- Muralidhar Addabaddi)/Jyothi Addabaddi  (-- Dattatreya Pujar)/Vishal Pujar  (-- )"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Godavari Rohidekar (b. 1925, d. 1980)  (-- Muralidhar Addabaddi)/Jyothi Addabaddi  (-- Dattatreya Pujar)/Anagha Pujar  (-- )"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Vatsala Rohidekar (b. 1928, d. 1953)  (-- Raghavendra Jagirdar)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Vatsala Rohidekar (b. 1928, d. 1953)  (-- Raghavendra Jagirdar)/Pushpa  (-- )"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Vatsala Rohidekar (b. 1928, d. 1953)  (-- Raghavendra Jagirdar)/Pushpa  (-- )/(no name)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Raghunath Rao Rohidekar (b. 1893, d. 1949)  (-- Janaki Kodagli)/Vatsala Rohidekar (b. 1928, d. 1953)  (-- Raghavendra Jagirdar)/Pushpa  (-- )/(no name)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Tulsakka Rohidekar (b. 1916)  (-- Vaman Rao Mirji)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Tulsakka Rohidekar (b. 1916)  (-- Vaman Rao Mirji)/(no name)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Tulsakka Rohidekar (b. 1916)  (-- Vaman Rao Mirji)/(no name)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Tulsakka Rohidekar (b. 1916)  (-- Vaman Rao Mirji)/(no name)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Tulsakka Rohidekar (b. 1916)  (-- Vaman Rao Mirji)/(no name)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Tulsakka Rohidekar (b. 1916)  (-- Vaman Rao Mirji)/(no name)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Usha  (-- Vaman Rao)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Usha  (-- Vaman Rao)/Sudharshan Harihar  (-- Suma Sudharshan)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Usha  (-- Vaman Rao)/Sudharshan Harihar  (-- Suma Sudharshan)/Suhas Harihar  (-- Ritinder Kaur)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Usha  (-- Vaman Rao)/Sudharshan Harihar  (-- Suma Sudharshan)/Suhas Harihar  (-- Ritinder Kaur)/Harihar"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Usha  (-- Vaman Rao)/Vasanthi ‘Bhagi’ Harish  (-- K Harish)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Usha  (-- Vaman Rao)/Vasanthi ‘Bhagi’ Harish  (-- K Harish)/K H Anirudh"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Jinki Prema  (-- Dr M V Mahishi)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Jinki Prema  (-- Dr M V Mahishi)/Ravindra / Anil? Anil? / Anil? // (d. 2010)  (-- Dr Rajini)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Jinki Prema  (-- Dr M V Mahishi)/Ravindra / Anil? Anil? / Anil? // (d. 2010)  (-- Dr Rajini)/Paavni"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Jinki Prema  (-- Dr M V Mahishi)/Snehalata / Appu Appu / Appu //  (-- Vinayak Desai)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Jinki Prema  (-- Dr M V Mahishi)/Snehalata / Appu Appu / Appu //  (-- Vinayak Desai)/Sapna Desai"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Jinki Prema  (-- Dr M V Mahishi)/Snehalata / Appu Appu / Appu //  (-- Vinayak Desai)/Sonali Desai"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Ramesh R Habbu (d. 2000)  (-- )"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Ramesh R Habbu (d. 2000)  (-- )/Habbu"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Ramesh R Habbu (d. 2000)  (-- )/Habbu"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Ramesh  (-- Leela)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Ramesh  (-- Leela)/Rashmi"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Ramesh  (-- Leela)/Vani"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Ramesh  (-- Leela)/Koushik"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Sudha/'Baby' 'Baby' 'Baby'/  (-- Gururajachav)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Sudha/'Baby' 'Baby' 'Baby'/  (-- Gururajachav)/Archana Kulkarni  (-- Shashidar Kulkarni)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Sudha/'Baby' 'Baby' 'Baby'/  (-- Gururajachav)/Archana Kulkarni  (-- Shashidar Kulkarni)/Aghamya Kulkarni"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Sudha/'Baby' 'Baby' 'Baby'/  (-- Gururajachav)/Arvind MG"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Vijaya / Viji Viji / Viji //  (-- Pralad Rao Wai)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Vijaya / Viji Viji / Viji //  (-- Pralad Rao Wai)/Dr Anand Rao  (-- Dr Prathibha)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Vijaya / Viji Viji / Viji //  (-- Pralad Rao Wai)/Dr Anand Rao  (-- Dr Prathibha)/Siddhanth Rao"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Vijaya / Viji Viji / Viji //  (-- Pralad Rao Wai)/Dr Anand Rao  (-- Dr Prathibha)/Rao"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Vijaya / Viji Viji / Viji //  (-- Pralad Rao Wai)/Prakash  (-- )"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Vijaya / Viji Viji / Viji //  (-- Pralad Rao Wai)/Prakash  (-- )/(no name)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Champakkabai Rohidekar (b. 1920, d. 1998)  (-- Narayana Rao Raghavendra Habbu)/Vijaya / Viji Viji / Viji //  (-- Pralad Rao Wai)/Prakash  (-- )/(no name)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Susheela Rohidekar (b. 1922, d. 1926)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Ranga Rao Rohidekar (b. 1924)  (-- Shankuntala Potdar)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Ranga Rao Rohidekar (b. 1924)  (-- Shankuntala Potdar)/Sridhar Rohidekar  (-- Anjana)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Ranga Rao Rohidekar (b. 1924)  (-- Shankuntala Potdar)/Sridhar Rohidekar  (-- Anjana)/Sameer Rohidekar"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Ranga Rao Rohidekar (b. 1924)  (-- Shankuntala Potdar)/Gururaj Rohidekar  (-- Manjula Benkai)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Ranga Rao Rohidekar (b. 1924)  (-- Shankuntala Potdar)/Gururaj Rohidekar  (-- Manjula Benkai)/Kiran Rohidekar (b. 1990)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Ranga Rao Rohidekar (b. 1924)  (-- Shankuntala Potdar)/Gururaj Rohidekar  (-- Manjula Benkai)/Gauri Rohidekar (b. 1996)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Ranga Rao Rohidekar (b. 1924)  (-- Shankuntala Potdar)/Veena Rohidekar  (-- Vasant Nagsampige)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Ranga Rao Rohidekar (b. 1924)  (-- Shankuntala Potdar)/Veena Rohidekar  (-- Vasant Nagsampige)/Pramod Nagsampige"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Ranga Rao Rohidekar (b. 1924)  (-- Shankuntala Potdar)/Veena Rohidekar  (-- Vasant Nagsampige)/Pavan Nagsampige"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Vasant Rao Rohidekar (b. 1932)  (-- Kaveri Parvatikar)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Vasant Rao Rohidekar (b. 1932)  (-- Kaveri Parvatikar)/Sreenivas Rohidekar  (-- Sunita)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Vasant Rao Rohidekar (b. 1932)  (-- Kaveri Parvatikar)/Venkatesh Rohidekar  (-- Venkana)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Vasant Rao Rohidekar (b. 1932)  (-- Kaveri Parvatikar)/Venkatesh Rohidekar  (-- Venkana)/Sharad Rohidekar (b. 1993)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Vasant Rao Rohidekar (b. 1932)  (-- Kaveri Parvatikar)/Venkatesh Rohidekar  (-- Venkana)/Ashwini Rohidekar (b. 7 Apr 1996)  (-- Madan)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Vasant Rao Rohidekar (b. 1932)  (-- Kaveri Parvatikar)/Geeta Rohidekar  (-- Panchamukhi)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Vasant Rao Rohidekar (b. 1932)  (-- Kaveri Parvatikar)/Geeta Rohidekar  (-- Panchamukhi)/Megha Panchmukhi"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Vasant Rao Rohidekar (b. 1932)  (-- Kaveri Parvatikar)/Nalini Rohidekar  (-- Arun Bellubbi)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Vasant Rao Rohidekar (b. 1932)  (-- Kaveri Parvatikar)/Nalini Rohidekar  (-- Arun Bellubbi)/Ajay Bellubbi"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Babu Rao Rohidekar (b. 1932)  (-- Mirji/Shantabai Shantabai/)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Babu Rao Rohidekar (b. 1932)  (-- Mirji/Shantabai Shantabai/)/Anuraddha Rohidekar  (-- Uday Savadatti)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Babu Rao Rohidekar (b. 1932)  (-- Mirji/Shantabai Shantabai/)/Anuraddha Rohidekar  (-- Uday Savadatti)/Rakshank Savadatti"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Babu Rao Rohidekar (b. 1932)  (-- Mirji/Shantabai Shantabai/)/Anuraddha Rohidekar  (-- Uday Savadatti)/Rohit Savadatti"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Babu Rao Rohidekar (b. 1932)  (-- Mirji/Shantabai Shantabai/)/Rohini Rohidekar  (-- Giridhar Deshpande)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Babu Rao Rohidekar (b. 1932)  (-- Mirji/Shantabai Shantabai/)/Rohini Rohidekar  (-- Giridhar Deshpande)/Aishwarya Deshpande"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Babu Rao Rohidekar (b. 1932)  (-- Mirji/Shantabai Shantabai/)/Shree Rohidekar  (-- Girish Dixit)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Babu Rao Rohidekar (b. 1932)  (-- Mirji/Shantabai Shantabai/)/Shree Rohidekar  (-- Girish Dixit)/Shashank"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Babu Rao Rohidekar (b. 1932)  (-- Mirji/Shantabai Shantabai/)/Shree Rohidekar  (-- Girish Dixit)/Nishant"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Raghavendra (Raghu) Rohidekar (b. 1934)  (-- Malati Kakmari)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Raghavendra (Raghu) Rohidekar (b. 1934)  (-- Malati Kakmari)/Rupa Rohidekar  (-- Govindaswamy)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Raghavendra (Raghu) Rohidekar (b. 1934)  (-- Malati Kakmari)/Rupa Rohidekar  (-- Govindaswamy)/Rashmi Govind (b. 1985)  (-- Raghavendra)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Raghavendra (Raghu) Rohidekar (b. 1934)  (-- Malati Kakmari)/Rupa Rohidekar  (-- Govindaswamy)/Rashmi Govind (b. 1985)  (-- Raghavendra)/Vishnu"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Raghavendra (Raghu) Rohidekar (b. 1934)  (-- Malati Kakmari)/Rupa Rohidekar  (-- Govindaswamy)/Ramya Govind (b. 1988)  (-- Hariprasad)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Raghavendra (Raghu) Rohidekar (b. 1934)  (-- Malati Kakmari)/Rupa Rohidekar  (-- Govindaswamy)/Ramya Govind (b. 1988)  (-- Hariprasad)/(no name) (b. 2 Nov 2020)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Raghavendra (Raghu) Rohidekar (b. 1934)  (-- Malati Kakmari)/Satish Rohidekar  (-- Chitra Srinivasan)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Raghavendra (Raghu) Rohidekar (b. 1934)  (-- Malati Kakmari)/Satish Rohidekar  (-- Chitra Srinivasan)/Akhil Rohidekar"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Raghavendra (Raghu) Rohidekar (b. 1934)  (-- Malati Kakmari)/Indumati Rohidekar  (-- Krishnamurthy)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Raghavendra (Raghu) Rohidekar (b. 1934)  (-- Malati Kakmari)/Indumati Rohidekar  (-- Krishnamurthy)/Dilip Krishnamurthy (b. 1990)  (-- Dhruti Ramya)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Raghavendra (Raghu) Rohidekar (b. 1934)  (-- Malati Kakmari)/Krishnamurthy Rohidekar  (-- Lakshmi)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Laxman Rao Rohidekar (b. 1847, d. 1934)  (-- Renubai)/Krishnaji Laxman Rohidekar (b. 1899, d. 1964)  (-- Venkubai)/Raghavendra (Raghu) Rohidekar (b. 1934)  (-- Malati Kakmari)/Krishnamurthy Rohidekar  (-- Lakshmi)/Nikhil Rohidekar"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Anand Rao Rohidekar (d. 1895)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Bhimka Rao Rohidekar (d. 1920)  (-- Radhabai)"
mkdir /tmp/"/Venkat Rao Rohidekar (b. 1825)  (-- Tarabai)/Venkawwa Rohidekar"
