mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Bhimka Anand Rao (-- Radhabai)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Anand Rao"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Anand Rao/Venkawwa Rohidekar"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Renubai)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Venkatesh Rohidekar (-- Rangubai Padki)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Ramachandra Rohidekar (-- Sitabai Anikhindi)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Ramachandra Rohidekar (-- Sitabai Anikhindi)/Puttaka Rohidekar (-- Chakarapani Bangalore Krishnaswamny)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Ramachandra Rohidekar (-- Sitabai Anikhindi)/Puttaka Rohidekar (-- Chakarapani Bangalore Krishnaswamny)/Madhavi BC (-- Narayan)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Ramachandra Rohidekar (-- Sitabai Anikhindi)/[Chakarapani -- Lakshmi?]"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Ramachandra Rohidekar (-- Sitabai Anikhindi)/[Chakarapani -- Lakshmi?]/Sindhoo BC (-- Ganesh)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Ramachandra Rohidekar (-- Sitabai Anikhindi)/[Chakarapani -- Lakshmi?]/Sindhoo BC (-- Ganesh)/Tanvi"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Ramachandra Rohidekar (-- Sitabai Anikhindi)/Lallakka Rohidekar (-- Narsimhamurthy DP)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Ramachandra Rohidekar (-- Sitabai Anikhindi)/Lallakka Rohidekar (-- Narsimhamurthy DP)/Pujitha Nagarajan"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Ramachandra Rohidekar (-- Sitabai Anikhindi)/Lallakka Rohidekar (-- Narsimhamurthy DP)/Jeevan Bharadhwaj DN (-- Tejasvi N. Rao)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Ramachandra Rohidekar (-- Sitabai Anikhindi)/Lallakka Rohidekar (-- Narsimhamurthy DP)/Shreeneedhi DN (-- Rashmi)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Ramachandra Rohidekar (-- Sitabai Anikhindi)/Sanvi"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Ramachandra Rohidekar (-- Sitabai Anikhindi)/Raghanath/Gopal Rohidekar (-- Radha)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Ramachandra Rohidekar (-- Sitabai Anikhindi)/Raghanath/Gopal Rohidekar (-- Radha)/Rajiva Rohidekar (-- Rohini / Amruta)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Ramachandra Rohidekar (-- Sitabai Anikhindi)/Raghanath/Gopal Rohidekar (-- Radha)/Rajiva Rohidekar (-- Rohini / Amruta)/??"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Ramachandra Rohidekar (-- Sitabai Anikhindi)/Raghanath/Gopal Rohidekar (-- Radha)/Rahul Rohidekar (-- Rashmi)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Ramachandra Rohidekar (-- Sitabai Anikhindi)/Nirmala/Asha Rohidekar (-- Ashok Sadarjoshi)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Ramachandra Rohidekar (-- Sitabai Anikhindi)/Jayaraj Rohidekar (-- Vijaya Sadarjoshi)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Ramachandra Rohidekar (-- Sitabai Anikhindi)/Jayaraj Rohidekar (-- Vijaya Sadarjoshi)/Ajay Rohidekar"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Ramachandra Rohidekar (-- Sitabai Anikhindi)/Jayaraj Rohidekar (-- Vijaya Sadarjoshi)/Prema Rohidekar (-- Prakash Kulkarni)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Ramachandra Rohidekar (-- Sitabai Anikhindi)/Jayaraj Rohidekar (-- Vijaya Sadarjoshi)/Prema Rohidekar (-- Prakash Kulkarni)/Poornima Kulkarni"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Ramachandra Rohidekar (-- Sitabai Anikhindi)/Jayaraj Rohidekar (-- Vijaya Sadarjoshi)/Prema Rohidekar (-- Prakash Kulkarni)/Prasanna Kulkarni"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Shamaji Rohidekar (-- Laxmibai Rama)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Shamaji Rohidekar (-- Laxmibai Rama)/Ravindra Rohidekar (-- Snehalata Rao)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Shamaji Rohidekar (-- Laxmibai Rama)/Ravindra Rohidekar (-- Snehalata Rao)/Gautum Rohidekar <!-- (-- Aparna) -->"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Shamaji Rohidekar (-- Laxmibai Rama)/Ravindra Rohidekar (-- Snehalata Rao)/Puneet Rohidekar"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Shamaji Rohidekar (-- Laxmibai Rama)/Meenakshi Rohidekar (-- Sudhir Sarnobat)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Shamaji Rohidekar (-- Laxmibai Rama)/Meenakshi Rohidekar (-- Sudhir Sarnobat)/Prakash Sarnobat"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Shamaji Rohidekar (-- Laxmibai Rama)/Meenakshi Rohidekar (-- Sudhir Sarnobat)/Sridhar Sarnobat"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Shamaji Rohidekar (-- Laxmibai Rama)/Meenakshi Rohidekar (-- Sudhir Sarnobat)/Priya Sarnobat (-- ??)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Shamaji Rohidekar (-- Laxmibai Rama)/Meenakshi Rohidekar (-- Sudhir Sarnobat)/Priya Sarnobat (-- ??)/??"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Shamaji Rohidekar (-- Laxmibai Rama)/Srinivas Rohidekar"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Shamaji Rohidekar (-- Laxmibai Rama)/(stillborn - no name) Rohidekar"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Shamaji Rohidekar (-- Laxmibai Rama)/Deepak Rohidekar (-- Anupama)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Shamaji Rohidekar (-- Laxmibai Rama)/Deepak Rohidekar (-- Anupama)/Gaurav Rohidekar"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Bagavanth Rohidekar (-- Krishna/Shanthabai Taalikoti)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Bagavanth Rohidekar (-- Krishna/Shanthabai Taalikoti)/Manjula Rohidekar (-- Shamsundar Bengeri)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Bagavanth Rohidekar (-- Krishna/Shanthabai Taalikoti)/Manjula Rohidekar (-- Shamsundar Bengeri)/Megha Bengeri (-- Jagdish)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Bagavanth Rohidekar (-- Krishna/Shanthabai Taalikoti)/Manjula Rohidekar (-- Shamsundar Bengeri)/Megha Bengeri (-- Jagdish)/??"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Bagavanth Rohidekar (-- Krishna/Shanthabai Taalikoti)/Manjula Rohidekar (-- Shamsundar Bengeri)/Amit Bengeri (-- Varada)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Bagavanth Rohidekar (-- Krishna/Shanthabai Taalikoti)/Manjula Rohidekar (-- Shamsundar Bengeri)/Amit Bengeri (-- Varada)/??"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Bagavanth Rohidekar (-- Krishna/Shanthabai Taalikoti)/Aadya Bengeri"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Bagavanth Rohidekar (-- Krishna/Shanthabai Taalikoti)/Parimala Rohidekar (-- Sham Gombi)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Bagavanth Rohidekar (-- Krishna/Shanthabai Taalikoti)/Parimala Rohidekar (-- Sham Gombi)/Soudamini Gombi (-- Yoga)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Bagavanth Rohidekar (-- Krishna/Shanthabai Taalikoti)/Parimala Rohidekar (-- Sham Gombi)/Soudamini Gombi (-- Yoga)/Kush"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Bagavanth Rohidekar (-- Krishna/Shanthabai Taalikoti)/Parimala Rohidekar (-- Sham Gombi)/Sindhu Gombi (-- ??)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Bagavanth Rohidekar (-- Krishna/Shanthabai Taalikoti)/Anand Rohidekar (-- Vidya Rao)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Bagavanth Rohidekar (-- Krishna/Shanthabai Taalikoti)/Anand Rohidekar (-- Vidya Rao)/Bhavana Rohidekar (-- Durgaprasad Bilagi)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Bagavanth Rohidekar (-- Krishna/Shanthabai Taalikoti)/Anand Rohidekar (-- Vidya Rao)/Bhavana Rohidekar (-- Durgaprasad Bilagi)/Swaraat"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Bagavanth Rohidekar (-- Krishna/Shanthabai Taalikoti)/Venkatesh Rohidekar (-- Latha Kulkarni)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Bagavanth Rohidekar (-- Krishna/Shanthabai Taalikoti)/Madhav Rohidekar"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (Sumitra Dani / Geetabai)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (Sumitra Dani / Geetabai)/Vinod Rohidekar (-- Vasudha Kadiyali)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (Sumitra Dani / Geetabai)/Vinod Rohidekar (-- Vasudha Kadiyali)/Vibhas Rohidekar (-- ??)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (Sumitra Dani / Geetabai)/Vinod Rohidekar (-- Vasudha Kadiyali)/Vandita Rohidekar"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (Sumitra Dani / Geetabai)/Vidya Rohidekar (-- Vaman Simha)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (Sumitra Dani / Geetabai)/Vidya Rohidekar (-- Vaman Simha)/Meghana Simha (-- Minaz Sajan)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (Sumitra Dani / Geetabai)/Vidya Rohidekar (-- Vaman Simha)/Meghana Simha (-- Minaz Sajan)/??"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (Sumitra Dani / Geetabai)/Vidya Rohidekar (-- Vaman Simha)/Meghana Simha (-- Minaz Sajan)/??"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (Sumitra Dani / Geetabai)/Vidya Rohidekar (-- Vaman Simha)/Tejashree Simha (-- Vineeth)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (Sumitra Dani / Geetabai)/Vilas Rohidekar (-- Usha S.G.)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (Sumitra Dani / Geetabai)/Veena Rohidekar (-- Jayprakash)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (Sumitra Dani / Geetabai)/Veena Rohidekar (-- Jayprakash)/Ketaki Jayaprakash"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (Sumitra Dani / Geetabai)/Vijay Rohidekar (-- Anuradha Kulkarni)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (Sumitra Dani / Geetabai)/Vijay Rohidekar (-- Anuradha Kulkarni)/Poorvi Rohidekar"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (Sumitra Dani / Geetabai)/Vijay Rohidekar (-- Anuradha Kulkarni)/Varsha Rohidekar"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (Sumitra Dani / Geetabai)/Vasanti Rohidekar (-- Vasudevan)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (Sumitra Dani / Geetabai)/Vasanti Rohidekar (-- Vasudevan)/Vallabh Vasudevan"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (Sumitra Dani / Geetabai)/Vasanti Rohidekar (-- Vasudevan)/Vaibhav Vasudevan"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Hanumanth Rao Rohidekar (Sumitra Dani / Geetabai)/(no name) Rohidekar"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Godavari Rohidekar (-- Muralidhar Adabaddi)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Godavari Rohidekar (-- Muralidhar Adabaddi)/Suresh Adabaddi (-- Vatsala / Vijaya Kshirsagar )"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Godavari Rohidekar (-- Muralidhar Adabaddi)/Suresh Adabaddi (-- Vatsala / Vijaya Kshirsagar )/'Peetu' Sandeep Adabaddi"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Godavari Rohidekar (-- Muralidhar Adabaddi)/Suresh Adabaddi (-- Vatsala / Vijaya Kshirsagar )/'Cheetu' Sagar Adabaddi (-- ??)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Godavari Rohidekar (-- Muralidhar Adabaddi)/Suresh Adabaddi (-- Vatsala / Vijaya Kshirsagar )/'Cheetu' Sagar Adabaddi (-- ??)/??"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Godavari Rohidekar (-- Muralidhar Adabaddi)/Suresh Adabaddi (-- Vatsala / Vijaya Kshirsagar )/'Cheetu' Sagar Adabaddi (-- ??)/??"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Godavari Rohidekar (-- Muralidhar Adabaddi)/Sulabha Rao Adabaddi <!-- Shuba after marriage --> (-- Raghavendra Rao S)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Godavari Rohidekar (-- Muralidhar Adabaddi)/Sarala Addabaddi (-- Surendhra Muthalik)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Godavari Rohidekar (-- Muralidhar Adabaddi)/Sarala Addabaddi (-- Surendhra Muthalik)/Archana Muthalik (-- Gururaj Beloli)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Godavari Rohidekar (-- Muralidhar Adabaddi)/Sarala Addabaddi (-- Surendhra Muthalik)/Archana Muthalik (-- Gururaj Beloli)/?? <!-- daughter -->"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Godavari Rohidekar (-- Muralidhar Adabaddi)/Sarala Addabaddi (-- Surendhra Muthalik)/Archana Muthalik (-- Gururaj Beloli)/?? <!-- daughter -->"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Godavari Rohidekar (-- Muralidhar Adabaddi)/Sarala Addabaddi (-- Surendhra Muthalik)/Vandana (-- Amit Umrani)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Godavari Rohidekar (-- Muralidhar Adabaddi)/Sarala Addabaddi (-- Surendhra Muthalik)/Meghana (-- Anant Mahajan)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Godavari Rohidekar (-- Muralidhar Adabaddi)/Jyothi Adabaddi			 (-- Dattatreya Pujar)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Godavari Rohidekar (-- Muralidhar Adabaddi)/Jyothi Adabaddi			 (-- Dattatreya Pujar)/Vishal Pujar (-- ??)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Godavari Rohidekar (-- Muralidhar Adabaddi)/Jyothi Adabaddi			 (-- Dattatreya Pujar)/Anagha Pujar (-- ??)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Vatsala Rohidekar (-- Raghavendra Jagirdar)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Vatsala Rohidekar (-- Raghavendra Jagirdar)/Pushpa ( -- SR Kulkarni)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Vatsala Rohidekar (-- Raghavendra Jagirdar)/Pushpa ( -- SR Kulkarni)/?? <!-- daughter? -->"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Raghunath Rao Rohidekar (-- Janaki Kodagli)/Vatsala Rohidekar (-- Raghavendra Jagirdar)/Pushpa ( -- SR Kulkarni)/?? <!-- daughter? -->"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Tulasakka Rohidekar (-- Vaman Rao Mirji)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Tulasakka Rohidekar (-- Vaman Rao Mirji)/??"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Tulasakka Rohidekar (-- Vaman Rao Mirji)/??"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Tulasakka Rohidekar (-- Vaman Rao Mirji)/??"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Tulasakka Rohidekar (-- Vaman Rao Mirji)/??"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Tulasakka Rohidekar (-- Vaman Rao Mirji)/??"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Chmpakka Rohidekar (-- ?? Habbu)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Chmpakka Rohidekar (-- ?? Habbu)/Usha (Vaman Rao)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Chmpakka Rohidekar (-- ?? Habbu)/Usha (Vaman Rao)/V Sudharshan Harihar (-- Suma Sudharshan)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Chmpakka Rohidekar (-- ?? Habbu)/Usha (Vaman Rao)/V Sudharshan Harihar (-- Suma Sudharshan)/Suhas Harihar (-- Ritinder Kaur)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Chmpakka Rohidekar (-- ?? Habbu)/Usha (Vaman Rao)/V Sudharshan Harihar (-- Suma Sudharshan)/Suhas Harihar (-- Ritinder Kaur)/??"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Chmpakka Rohidekar (-- ?? Habbu)/Usha (Vaman Rao)/Vasanthi ‘Bhagi’ Harish ( -- K Harish)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Chmpakka Rohidekar (-- ?? Habbu)/Usha (Vaman Rao)/Vasanthi ‘Bhagi’ Harish ( -- K Harish)/K H Anirudh <!-- son -->"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Chmpakka Rohidekar (-- ?? Habbu)/Jinki Prema (-- ??)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Chmpakka Rohidekar (-- ?? Habbu)/Jinki Prema (-- ??)/Snehalatha / Appu? (-- ??)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Chmpakka Rohidekar (-- ?? Habbu)/Jinki Prema (-- ??)/Snehalatha / Appu? (-- ??)/Sapna"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Chmpakka Rohidekar (-- ?? Habbu)/Jinki Prema (-- ??)/Snehalatha / Appu? (-- ??)/Sonali"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Chmpakka Rohidekar (-- ?? Habbu)/Jinki Prema (-- ??)/Ravindra / Anil?"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Chmpakka Rohidekar (-- ?? Habbu)/Jinki Prema (-- ??)/Ravindra / Anil?/Paavni"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Chmpakka Rohidekar (-- ?? Habbu)/Ramesh"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Chmpakka Rohidekar (-- ?? Habbu)/Ramesh/Rashmi"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Chmpakka Rohidekar (-- ?? Habbu)/Ramesh/Vani"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Chmpakka Rohidekar (-- ?? Habbu)/Ramesh/Koushik"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Chmpakka Rohidekar (-- ?? Habbu)/'Baby'/ Sudha (-- Gururaj)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Chmpakka Rohidekar (-- ?? Habbu)/'Baby'/ Sudha (-- Gururaj)/Archana Kulkarni <!-- Facebook --> (-- Shashidar Kulkarni)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Chmpakka Rohidekar (-- ?? Habbu)/'Baby'/ Sudha (-- Gururaj)/Archana Kulkarni <!-- Facebook --> (-- Shashidar Kulkarni)/Aghamya Kulkarni"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Chmpakka Rohidekar (-- ?? Habbu)/'Baby'/ Sudha (-- Gururaj)/MG Arvind (-- Ruthika <!--Facebook-->)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Chmpakka Rohidekar (-- ?? Habbu)/Vijaya / Viji (-- Pralad Rao)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Chmpakka Rohidekar (-- ?? Habbu)/Vijaya / Viji (-- Pralad Rao)/<!-- Dr --> Anand Rao"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Chmpakka Rohidekar (-- ?? Habbu)/Vijaya / Viji (-- Pralad Rao)/<!-- Dr --> Anand Rao/Siddhanth"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Chmpakka Rohidekar (-- ?? Habbu)/Vijaya / Viji (-- Pralad Rao)/<!-- Dr --> Anand Rao/??"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Chmpakka Rohidekar (-- ?? Habbu)/Vijaya / Viji (-- Pralad Rao)/Prakash"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Chmpakka Rohidekar (-- ?? Habbu)/Vijaya / Viji (-- Pralad Rao)/Prakash/??"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Chmpakka Rohidekar (-- ?? Habbu)/Vijaya / Viji (-- Pralad Rao)/Prakash/??"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Susheela Rohidekar"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Vasant Rohidekar (-- Kaveri Parvatikar)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Vasant Rohidekar (-- Kaveri Parvatikar)/Sreenivas Rohidekar (-- ??)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Vasant Rohidekar (-- Kaveri Parvatikar)/Venkatesh Rohidekar (-- Venkana)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Vasant Rohidekar (-- Kaveri Parvatikar)/Venkatesh Rohidekar (-- Venkana)/Sharad Rohidekar"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Vasant Rohidekar (-- Kaveri Parvatikar)/Venkatesh Rohidekar (-- Venkana)/Ashwhini Rohidekar (-- Madan)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Ranga Rao Rohidekar (-- Shankuntala Potdar)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Ranga Rao Rohidekar (-- Shankuntala Potdar)/Sridhar Rohidekar (-- Anjana Mathad)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Ranga Rao Rohidekar (-- Shankuntala Potdar)/Sridhar Rohidekar (-- Anjana Mathad)/Sameer Rohidekar"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Ranga Rao Rohidekar (-- Shankuntala Potdar)/Gururaj Rohidekar (-- Manjula Benkal)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Ranga Rao Rohidekar (-- Shankuntala Potdar)/Gururaj Rohidekar (-- Manjula Benkal)/Kiran Rohidekar"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Ranga Rao Rohidekar (-- Shankuntala Potdar)/Gururaj Rohidekar (-- Manjula Benkal)/Rachana 'Gauri' Rohidekar"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Ranga Rao Rohidekar (-- Shankuntala Potdar)/Veena (-- Vasant Nagsampige)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Ranga Rao Rohidekar (-- Shankuntala Potdar)/Veena (-- Vasant Nagsampige)/Pramod Nagsampige"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Ranga Rao Rohidekar (-- Shankuntala Potdar)/Veena (-- Vasant Nagsampige)/Pavan Nagsampige"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Babu Rao Rohidekar"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Babu Rao Rohidekar/Anuraddha Rohidekar"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Babu Rao Rohidekar/Rohini Rohidekar"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Babu Rao Rohidekar/Rohini Rohidekar/Aishwarya"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Babu Rao Rohidekar/Shree Rohidekar"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Babu Rao Rohidekar/Shree Rohidekar/Shashank"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Babu Rao Rohidekar/Shree Rohidekar/??"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Raghavendra Rohidekar"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Raghavendra Rohidekar/Rupa Rohidekar (-- Govindaswamy)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Raghavendra Rohidekar/Rupa Rohidekar (-- Govindaswamy)/Rashmi Govind (-- Raghavendra)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Raghavendra Rohidekar/Rupa Rohidekar (-- Govindaswamy)/Rashmi Govind (-- Raghavendra)/Vishnu"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Raghavendra Rohidekar/Rupa Rohidekar (-- Govindaswamy)/Ramya Govind (-- Srinivas?)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Raghavendra Rohidekar/Satish Rohidekar (-- Chitra Srinivasan)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Raghavendra Rohidekar/Satish Rohidekar (-- Chitra Srinivasan)/Akhil Rohidekar"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Raghavendra Rohidekar/Indira (-- Krishnamurthy)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Raghavendra Rohidekar/Indira (-- Krishnamurthy)/Dhilip Krishnamurthy"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Raghavendra Rohidekar/Krishnamurthy Rohidekar (-- Lakshmi)"
mkdir /tmp/"/Venkatesh Rohidekar (-- Tarabai)/Laxman V Rohidekar (-- Sitabai)/Krishnaji Laxman Rohidekar (-- Venkubai)/Raghavendra Rohidekar/Krishnamurthy Rohidekar (-- Lakshmi)/Nikhil Rohidekar"
mkdir /tmp/""
