mkdir /tmp/"@I402@	Khatavkar, null"
mkdir /tmp/"@I414@	Inamdar, Krishnamurthy"
mkdir /tmp/"@I317@	Deshpande, Sanjay"
mkdir /tmp/"@I426@	Inamdar, null"
mkdir /tmp/"@I305@	Deshpande, Rohan"
mkdir /tmp/"@I438@	Hallur, Kritina Pramila"
mkdir /tmp/"@I2@	Sarnobat, Prakash"
mkdir /tmp/"@I81@	Rohidekar, Varsha"
mkdir /tmp/"@I93@	"
mkdir /tmp/"@I208@	null, Laxman"
mkdir /tmp/"@I329@	null"
mkdir /tmp/"@I403@	"
mkdir /tmp/"@I306@	Deshpande, Nikita"
mkdir /tmp/"@I415@	Inamdar, Venugopal"
mkdir /tmp/"@I427@	Inamdar, Pavaman"
mkdir /tmp/"@I3@	Rohidekar, Meenakshi"
mkdir /tmp/"@I80@	Rohidekar, Poorvi"
mkdir /tmp/"@I92@	"
mkdir /tmp/"@I209@	Sarnobat, Balkrishna"
mkdir /tmp/"@I439@	null, Gangabai"
mkdir /tmp/"@I318@	Deshpande, Seema"
mkdir /tmp/"@I315@	Deshpande, Murulidhar"
mkdir /tmp/"@I424@	"
mkdir /tmp/"@I303@	Deshpande, Pradeep"
mkdir /tmp/"@I436@	null, Meghana"
mkdir /tmp/"@I218@	Sarnobat, Anuja"
mkdir /tmp/"@I339@	Sarnobat, Leela"
mkdir /tmp/"@I448@	Karanam, Susislendra Rao"
mkdir /tmp/"@I206@	Deshmukh, Megh"
mkdir /tmp/"@I327@	null"
mkdir /tmp/"@I400@	Gajbar, Sameer"
mkdir /tmp/"@I412@	Karanam, Narasappa Lakshmi"
mkdir /tmp/"@I4@	Rohidekar, Shamaji"
mkdir /tmp/"@I71@	Rohidekar, Rahul"
mkdir /tmp/"@I83@	null, Peetu"
mkdir /tmp/"@I95@	"
mkdir /tmp/"@I109@	Rohidekar, Sreenivas"
mkdir /tmp/"@I304@	null"
mkdir /tmp/"@I413@	Inamdar, Shobha"
mkdir /tmp/"@I425@	"
mkdir /tmp/"@I207@	Deshmukh, Sawani"
mkdir /tmp/"@I328@	Sarnobat, Nithin"
mkdir /tmp/"@I437@	Hallur, Krishna"
mkdir /tmp/"@I316@	null, Leela"
mkdir /tmp/"@I449@	Karanam, Lakshmi Narsappa"
mkdir /tmp/"@I401@	"
mkdir /tmp/"@I5@	Sarnobat, Priya"
mkdir /tmp/"@I70@	null, Rajiva"
mkdir /tmp/"@I82@	null, Vallabh"
mkdir /tmp/"@I94@	"
mkdir /tmp/"@I219@	Sarnobat, Damodar Sripad"
mkdir /tmp/"@I6@	Sarnobat, Sudhir"
mkdir /tmp/"@I190@	Naik, Vikram"
mkdir /tmp/"@I406@	Katti, Rajat"
mkdir /tmp/"@I418@	Hallur, Ravi"
mkdir /tmp/"@I309@	null, Sarala"
mkdir /tmp/"@I7@	Rohidekar, Deepak"
mkdir /tmp/"@I192@	Halliyal, Arvind"
mkdir /tmp/"@I191@	null, Gayatri"
mkdir /tmp/"@I407@	null, Yamuna"
mkdir /tmp/"@I419@	Hallur, Geetha"
mkdir /tmp/"@I404@	Gajbar, null"
mkdir /tmp/"@I416@	Inamdar, Bhouma"
mkdir /tmp/"@I90@	"
mkdir /tmp/"@I8@	null, Anupama"
mkdir /tmp/"@I91@	"
mkdir /tmp/"@I319@	null, Sangeeta"
mkdir /tmp/"@I428@	Inamdar, Gauri"
mkdir /tmp/"@I307@	"
mkdir /tmp/"@I405@	Katti, Vilas B"
mkdir /tmp/"@I9@	"
mkdir /tmp/"@I308@	Deshpande, Vasant"
mkdir /tmp/"@I417@	Hallur, null"
mkdir /tmp/"@I429@	Hallur, Ritwik Prajwal"
mkdir /tmp/"@I248@	null"
mkdir /tmp/"@I369@	Kanago, Shilpa"
mkdir /tmp/"@I127@	"
mkdir /tmp/"@I139@	null, Usha"
mkdir /tmp/"@I103@	null, Ramesh ?"
mkdir /tmp/"@I212@	Sarnobat, Neeelkanthand"
mkdir /tmp/"@I333@	Sarnobat, Bhagwant"
mkdir /tmp/"@I442@	"
mkdir /tmp/"@I115@	"
mkdir /tmp/"@I200@	null, Shreya"
mkdir /tmp/"@I321@	Deshpande, Aditi"
mkdir /tmp/"@I454@	Karanam, Raghunath Rao"
mkdir /tmp/"@I357@	Jinralkar, Shreyas"
mkdir /tmp/"@I466@	Tamraparni, Madhumathi"
mkdir /tmp/"@I224@	Sarnobat, Ramesh"
mkdir /tmp/"@I345@	Sarnobat, Damodar"
mkdir /tmp/"@I478@	Kulkarni, Shamu"
mkdir /tmp/"@I430@	Hallur, Lakshmi Roma"
mkdir /tmp/"@I249@	"
mkdir /tmp/"@I479@	Sarnobat, Vijay"
mkdir /tmp/"@I358@	null, Aarya"
mkdir /tmp/"@I116@	Rohidekar, Sameer"
mkdir /tmp/"@I128@	Rohidekar, Nikhil"
mkdir /tmp/"@I201@	null, Father of Shreya"
mkdir /tmp/"@I322@	Baxi, null"
mkdir /tmp/"@I431@	Dandin, Govind Rao"
mkdir /tmp/"@I104@	null, 'Baby'"
mkdir /tmp/"@I310@	Deshpande, Ajit"
mkdir /tmp/"@I443@	null, Yamuna"
mkdir /tmp/"@I225@	Dabeer, Nutan"
mkdir /tmp/"@I346@	Sarnobat, Anjali"
mkdir /tmp/"@I455@	Karanam, Bhargavi"
mkdir /tmp/"@I213@	Sarnobat, Vishnu"
mkdir /tmp/"@I334@	Sarnobat, Gajanan (Pandit)"
mkdir /tmp/"@I467@	null, Pavithra"
mkdir /tmp/"@I149@	Sarnobat, Uday"
mkdir /tmp/"@I125@	null, Krishnamurthy"
mkdir /tmp/"@I355@	Desai, Kaustub"
mkdir /tmp/"@I464@	Tamraparni, Raghanaj"
mkdir /tmp/"@I137@	Rao, Vidya"
mkdir /tmp/"@I222@	Sarnobat, Srinivas (Bapusaheb)"
mkdir /tmp/"@I343@	Kulkarni, Ujwala (Tippurli)"
mkdir /tmp/"@I476@	null, Chabi"
mkdir /tmp/"@I101@	null, Usha"
mkdir /tmp/"@I258@	Kulkarni, Rupa"
mkdir /tmp/"@I379@	Sarnobat, Sankalp"
mkdir /tmp/"@I488@	(Mumbai), null"
mkdir /tmp/"@I113@	Rohidekar, Indumati"
mkdir /tmp/"@I246@	null"
mkdir /tmp/"@I367@	Naik, Murli"
mkdir /tmp/"@I210@	null, Ancestors"
mkdir /tmp/"@I331@	Sarnobat, Konher (Tatyasaheb)"
mkdir /tmp/"@I440@	"
mkdir /tmp/"@I452@	Karanam, Sridhar Rao"
mkdir /tmp/"@I259@	Deshpande, Pallavi / Nita?"
mkdir /tmp/"@I138@	Kulkarni, Latha"
mkdir /tmp/"@I114@	Rohidekar, Krishnamurthy"
mkdir /tmp/"@I223@	Kulkarni, Padmavati"
mkdir /tmp/"@I344@	Sarnobat, Vithal"
mkdir /tmp/"@I453@	Karanam, null"
mkdir /tmp/"@I126@	null, Dhilip"
mkdir /tmp/"@I211@	Sarnobat, Sadashiv"
mkdir /tmp/"@I332@	Sarnobat, Shrikrishna"
mkdir /tmp/"@I465@	Tamraparni, Guruprasad"
mkdir /tmp/"@I247@	null"
mkdir /tmp/"@I368@	Sarnobat, Sudhavshu"
mkdir /tmp/"@I477@	null, Shalu"
mkdir /tmp/"@I102@	null, Jirki"
mkdir /tmp/"@I356@	null, Yashraj"
mkdir /tmp/"@I489@	(Mumbai), null"
mkdir /tmp/"@I320@	Deshpande, Nidhi"
mkdir /tmp/"@I441@	null, Tara"
mkdir /tmp/"@I107@	Rohidekar, Gururaj"
mkdir /tmp/"@I216@	Sarnobat, Hemal"
mkdir /tmp/"@I337@	Sarnobat, Vijaya"
mkdir /tmp/"@I446@	"
mkdir /tmp/"@I119@	Rohidekar, Gauri"
mkdir /tmp/"@I204@	Sarnobat, Rucha"
mkdir /tmp/"@I325@	Kulkarni (Jugul), Mandakini"
mkdir /tmp/"@I458@	null, Vijaya"
mkdir /tmp/"@I228@	Sarnobat, Umesh"
mkdir /tmp/"@I349@	null, Kshama"
mkdir /tmp/"@I313@	Deshpande, null"
mkdir /tmp/"@I422@	null, Parmila"
mkdir /tmp/"@I301@	Deshpande, Aditya"
mkdir /tmp/"@I434@	Muthkikar, Vinod"
mkdir /tmp/"@I17@	Rohidekar, Raghunath Rao"
mkdir /tmp/"@I29@	Rohidekar, Laxman V"
mkdir /tmp/"@I205@	Sarnobat, Sachi"
mkdir /tmp/"@I326@	Sarnobat, Deepak"
mkdir /tmp/"@I435@	Muthkikar, Kshama"
mkdir /tmp/"@I108@	Rohidekar, Veena"
mkdir /tmp/"@I314@	Deshpande, Amit"
mkdir /tmp/"@I447@	null, Shobha"
mkdir /tmp/"@I229@	Shrikhande, Ina"
mkdir /tmp/"@I459@	Karanam, Sri Vidya"
mkdir /tmp/"@I217@	Sarnobat, Adwait"
mkdir /tmp/"@I338@	Sarnobat, Shashikala"
mkdir /tmp/"@I302@	Deshpande, Nidhi"
mkdir /tmp/"@I411@	Hallur, Padmalatha"
mkdir /tmp/"@I423@	null, Sridevi"
mkdir /tmp/"@I16@	Rohidekar, Hanumanth Rao"
mkdir /tmp/"@I28@	Simha, Tejashri"
mkdir /tmp/"@I129@	Taalikoti, Krishna"
mkdir /tmp/"@I359@	Adke, Radha (Sadalga)"
mkdir /tmp/"@I468@	null, Anandthirtha"
mkdir /tmp/"@I226@	Sarnobat, Sayee Kar"
mkdir /tmp/"@I347@	Sarnobat, Shruti"
mkdir /tmp/"@I105@	null, Viji"
mkdir /tmp/"@I117@	null, Manjula"
mkdir /tmp/"@I311@	null"
mkdir /tmp/"@I420@	Hallur, Kavitha"
mkdir /tmp/"@I432@	Dandin, Shreya"
mkdir /tmp/"@I214@	Sarnobat, Vitthal"
mkdir /tmp/"@I335@	Sarnobat, Ravi"
mkdir /tmp/"@I444@	null, Pandu"
mkdir /tmp/"@I202@	null, Shashank"
mkdir /tmp/"@I323@	Baxi, Neha"
mkdir /tmp/"@I456@	Karanam, Madhav Rao"
mkdir /tmp/"@I19@	Rohidekar, Vinod"
mkdir /tmp/"@I118@	Rohidekar, Kiran"
mkdir /tmp/"@I227@	Sarnobat, Rahi"
mkdir /tmp/"@I348@	null, Medha"
mkdir /tmp/"@I457@	Karanam, Gururaj Rao"
mkdir /tmp/"@I215@	Sarnobat, Milind"
mkdir /tmp/"@I336@	Sarnobat, Venkatesh"
mkdir /tmp/"@I469@	null"
mkdir /tmp/"@I106@	Rohidekar, Sridhar"
mkdir /tmp/"@I300@	null"
mkdir /tmp/"@I421@	Hallur, Gururaj"
mkdir /tmp/"@I203@	null, Pallavi"
mkdir /tmp/"@I324@	Sarnobat, Manohar"
mkdir /tmp/"@I433@	Dandin, Sujan"
mkdir /tmp/"@I312@	Deshpande, null"
mkdir /tmp/"@I445@	null, Tangabai"
mkdir /tmp/"@I18@	null, Janaki"
mkdir /tmp/"@I288@	Deshpande, Srikrishna ('Shama Mama')"
mkdir /tmp/"@I167@	null, Aasha"
mkdir /tmp/"@I179@	Kulkarni, Aruna"
mkdir /tmp/"@I143@	Mutalik, null"
mkdir /tmp/"@I252@	Sabde, Tara ('Babi mami' / 'Tai ajji')"
mkdir /tmp/"@I373@	Gosavi, Ashwini (Hattargi)"
mkdir /tmp/"@I482@	Sarnobat, Sarojini"
mkdir /tmp/"@I155@	Sarnobat, Dattatraya"
mkdir /tmp/"@I361@	Sarnobat, Pushpa"
mkdir /tmp/"@I276@	Hallur, Sudheendra"
mkdir /tmp/"@I397@	Ghatigar, Ramakrishna"
mkdir /tmp/"@I131@	null, Jagirdar"
mkdir /tmp/"@I264@	Kulkarni, Abhijeet"
mkdir /tmp/"@I385@	Deshpande, Rajeev"
mkdir /tmp/"@I470@	Karanam, Srivathsa"
mkdir /tmp/"@I13@	Rohidekar, Puneet"
mkdir /tmp/"@I25@	Rohidekar, Vasanti"
mkdir /tmp/"@I37@	Rohidekar, Bagavanth"
mkdir /tmp/"@I49@	Rohidekar, Nirmala"
mkdir /tmp/"@I289@	null, Ramaa"
mkdir /tmp/"@I277@	Hallur, Shilpa"
mkdir /tmp/"@I398@	Khatavkar, null"
mkdir /tmp/"@I156@	null, Mother of Balakrishna"
mkdir /tmp/"@I168@	null, Lata"
mkdir /tmp/"@I132@	null, HHBBU"
mkdir /tmp/"@I362@	Hampiholi, Sirish"
mkdir /tmp/"@I471@	Karanam, Srinidhi"
mkdir /tmp/"@I144@	null, Venkana"
mkdir /tmp/"@I350@	Desai, Rajesh"
mkdir /tmp/"@I483@	Sarnobat (alive 2019, Miraj, Maharashtra), Sheelu"
mkdir /tmp/"@I265@	Deshpande, Sakharam ('babu mama')"
mkdir /tmp/"@I386@	null, Rashmi"
mkdir /tmp/"@I120@	Rohidekar, Rupa"
mkdir /tmp/"@I253@	Deshpande, Ravindra"
mkdir /tmp/"@I374@	Sarnobat, Annapurna"
mkdir /tmp/"@I12@	Rohidekar, Ravindra"
mkdir /tmp/"@I24@	Rohidekar, Vijay"
mkdir /tmp/"@I36@	Rohidekar, Ramachandra"
mkdir /tmp/"@I48@	Rohidekar, Raghanath"
mkdir /tmp/"@I189@	Naik, Aditya"
mkdir /tmp/"@I165@	Sarnobat, Kunja"
mkdir /tmp/"@I274@	Bhamare, Kamlesh"
mkdir /tmp/"@I395@	Ghatigar, Gouri"
mkdir /tmp/"@I177@	Sarnobat, Anupama"
mkdir /tmp/"@I262@	Kulkarni, Anant"
mkdir /tmp/"@I383@	Kulkarni, Prashant"
mkdir /tmp/"@I141@	null, Anuradha"
mkdir /tmp/"@I298@	"
mkdir /tmp/"@I153@	Sarnobat, Sharad"
mkdir /tmp/"@I286@	Jain, Neha"
mkdir /tmp/"@I250@	"
mkdir /tmp/"@I371@	Sarnobat, Shivram"
mkdir /tmp/"@I480@	Sarnobat, Vilas"
mkdir /tmp/"@I15@	Rohidekar, Gautum"
mkdir /tmp/"@I27@	Simha, Vaman"
mkdir /tmp/"@I39@	null, Vatsala"
mkdir /tmp/"@I299@	Deshpande, Dilip"
mkdir /tmp/"@I178@	Sarnobat, Ankur"
mkdir /tmp/"@I154@	Sarnobat, Balakrishna"
mkdir /tmp/"@I263@	Kulkarni, Akshata"
mkdir /tmp/"@I384@	Naik, Avinash"
mkdir /tmp/"@I166@	"
mkdir /tmp/"@I251@	Deshpande, Narayan R (('pandit mama' / 'dada mama')"
mkdir /tmp/"@I372@	Sarnobat, Trupti"
mkdir /tmp/"@I130@	Adabaddi, Casant"
mkdir /tmp/"@I287@	Adya, Srihari"
mkdir /tmp/"@I142@	null, Vasu"
mkdir /tmp/"@I275@	Deshpande, Nanda"
mkdir /tmp/"@I396@	Ghatigar, Geeta"
mkdir /tmp/"@I360@	Sarnobat, Bhakti"
mkdir /tmp/"@I481@	Sarnobat, Babu"
mkdir /tmp/"@I14@	Rao, Snehalata"
mkdir /tmp/"@I26@	Simha, Meghana"
mkdir /tmp/"@I38@	Rohidekar, Godavari"
mkdir /tmp/"@I147@	Sarnobat, Ramchandra"
mkdir /tmp/"@I256@	Deshpande, Pranav"
mkdir /tmp/"@I377@	Kulkarni, Gouri (Hubli)"
mkdir /tmp/"@I486@	null"
mkdir /tmp/"@I159@	"
mkdir /tmp/"@I244@	null"
mkdir /tmp/"@I365@	Kulkarni, (Ammangi)"
mkdir /tmp/"@I123@	null, Chitra"
mkdir /tmp/"@I135@	Bengeri, Sham Sardar"
mkdir /tmp/"@I268@	null, Kamala"
mkdir /tmp/"@I389@	Deshpande, Nisha"
mkdir /tmp/"@I111@	null, Govinthraja"
mkdir /tmp/"@I450@	null, Narsamma"
mkdir /tmp/"@I232@	Donwad, Sushila"
mkdir /tmp/"@I353@	null, Shravani"
mkdir /tmp/"@I462@	Karanam, Archana"
mkdir /tmp/"@I220@	null"
mkdir /tmp/"@I341@	Sarnobat, Kalpana"
mkdir /tmp/"@I474@	"
mkdir /tmp/"@I33@	Rohidekar, Venkatesh"
mkdir /tmp/"@I45@	Rohidekar, Raghu"
mkdir /tmp/"@I57@	Rohidekar, Venkatesh"
mkdir /tmp/"@I69@	null, Shreeneethi"
mkdir /tmp/"@I21@	Rohidekar, Vidya"
mkdir /tmp/"@I136@	Gombi, Sham"
mkdir /tmp/"@I245@	null"
mkdir /tmp/"@I366@	Sarnobat, Kirti"
mkdir /tmp/"@I475@	null, Choti"
mkdir /tmp/"@I148@	Ambikha Deshpande, Sitabai"
mkdir /tmp/"@I354@	Sarnobat, Kedar"
mkdir /tmp/"@I487@	"
mkdir /tmp/"@I112@	Rohidekar, Satish"
mkdir /tmp/"@I269@	Deshpande, Pramod"
mkdir /tmp/"@I124@	Rohidekar, Akhil"
mkdir /tmp/"@I257@	Deshpande, Rajendra"
mkdir /tmp/"@I378@	Sarnobat, Vaishnavi"
mkdir /tmp/"@I100@	"
mkdir /tmp/"@I221@	null, Rama"
mkdir /tmp/"@I342@	Deshpande, Prema (Karguppi)"
mkdir /tmp/"@I451@	null, Shantabai"
mkdir /tmp/"@I330@	Sarnobat, Sriram (Appasaheb)"
mkdir /tmp/"@I463@	Karanam, Abhishek"
mkdir /tmp/"@I44@	Rohidekar, Vasant"
mkdir /tmp/"@I56@	Rohidekar, Anand"
mkdir /tmp/"@I68@	null, Pujitha"
mkdir /tmp/"@I20@	"
mkdir /tmp/"@I32@	Rohidekar, Bhimka Anand Rao"
mkdir /tmp/"@I169@	null, Maya"
mkdir /tmp/"@I278@	Pujar, Chidamber"
mkdir /tmp/"@I399@	"
mkdir /tmp/"@I266@	Deshpande, Subbakka"
mkdir /tmp/"@I387@	Kulkarni, Varun"
mkdir /tmp/"@I145@	null"
mkdir /tmp/"@I157@	Sarnobat, Balkrishna"
mkdir /tmp/"@I121@	null, Rashmi"
mkdir /tmp/"@I230@	Sarnobat, Rahul"
mkdir /tmp/"@I351@	Jinralkar, Rupesh"
mkdir /tmp/"@I460@	Karanam, Phani Rao"
mkdir /tmp/"@I133@	null, Narsimhamurthy"
mkdir /tmp/"@I472@	null, Anushna"
mkdir /tmp/"@I254@	(Geetanjali), Radhika"
mkdir /tmp/"@I375@	Kulkarni, Aniruddha"
mkdir /tmp/"@I484@	"
mkdir /tmp/"@I363@	Wader, Chandrashekhar"
mkdir /tmp/"@I11@	Rama, Laxmibai"
mkdir /tmp/"@I23@	Rohidekar, Veina"
mkdir /tmp/"@I35@	null, Rangubai"
mkdir /tmp/"@I47@	Rohidekar, Lallakka"
mkdir /tmp/"@I59@	null, Suresh"
mkdir /tmp/"@I158@	"
mkdir /tmp/"@I267@	null, Champakka"
mkdir /tmp/"@I388@	Deshpande, Neeta"
mkdir /tmp/"@I255@	Deshpande, Deepthi"
mkdir /tmp/"@I376@	Sarnobat, Anulekha"
mkdir /tmp/"@I134@	"
mkdir /tmp/"@I146@	null, Narayan"
mkdir /tmp/"@I279@	Pujar, Archit"
mkdir /tmp/"@I110@	Rohidekar, Venkatesh"
mkdir /tmp/"@I340@	Sarnobat, Meena"
mkdir /tmp/"@I122@	null, Ramya"
mkdir /tmp/"@I461@	null, Ahalya"
mkdir /tmp/"@I364@	Hampiholi, Shubhan"
mkdir /tmp/"@I473@	Sarnobat, Kamalabai ("Atya")"
mkdir /tmp/"@I231@	Sarnobat, Ishan"
mkdir /tmp/"@I352@	Sarnobat, Shivani"
mkdir /tmp/"@I485@	"
mkdir /tmp/"@I22@	Rohidekar, Vilas"
mkdir /tmp/"@I34@	null, Radhabai"
mkdir /tmp/"@I46@	Rohidekar, Puttaka"
mkdir /tmp/"@I58@	Rohidekar, Madhav"
mkdir /tmp/"@I10@	Rohidekar, Gaurav"
mkdir /tmp/"@I183@	Kari, Suman"
mkdir /tmp/"@I292@	Deshpande, Shyam ('shama mama')"
mkdir /tmp/"@I195@	Gathikar, Ravi"
mkdir /tmp/"@I280@	Hallur, Seema"
mkdir /tmp/"@I171@	Kulkarni, Savita"
mkdir /tmp/"@I77@	Rohidekar, Vibhas"
mkdir /tmp/"@I89@	"
mkdir /tmp/"@I41@	Rohidekar, Tulasakka"
mkdir /tmp/"@I53@	Rohidekar, null"
mkdir /tmp/"@I65@	null, Chakarapani B.K."
mkdir /tmp/"@I196@	Gathikar, Mohit"
mkdir /tmp/"@I172@	Dariano, Lucia"
mkdir /tmp/"@I281@	Shah, Rohan"
mkdir /tmp/"@I184@	Sarnobat, Vandana"
mkdir /tmp/"@I390@	Naik, Nikhil"
mkdir /tmp/"@I160@	Sarnobat, Hanmanth"
mkdir /tmp/"@I293@	null, Maya"
mkdir /tmp/"@I88@	"
mkdir /tmp/"@I40@	Rohidekar, Krisnaji Laxman"
mkdir /tmp/"@I52@	Rohidekar, Srinivas"
mkdir /tmp/"@I64@	null, Sitabai"
mkdir /tmp/"@I76@	Rohidekar, Bhavana"
mkdir /tmp/"@I181@	Sarnobat, Purnima"
mkdir /tmp/"@I193@	Halliyal, Father of Arvind"
mkdir /tmp/"@I55@	Rohidekar, Parimala"
mkdir /tmp/"@I67@	null, Jeevan"
mkdir /tmp/"@I180@	Halliyal, Vasudhev"
mkdir /tmp/"@I79@	null, Ketaki"
mkdir /tmp/"@I31@	Kadiyali, Vasudha"
mkdir /tmp/"@I408@	Katti, Kris"
mkdir /tmp/"@I43@	Rohidekar, Ranganath"
mkdir /tmp/"@I194@	null, Mother of Arvind"
mkdir /tmp/"@I291@	Deshpande, Kiran"
mkdir /tmp/"@I170@	Sarnobat, Sachin"
mkdir /tmp/"@I182@	Deshmukh, Lalit"
mkdir /tmp/"@I66@	null, Madhavi"
mkdir /tmp/"@I78@	Rohidekar, Vandita"
mkdir /tmp/"@I290@	Deshpande, Keerthi"
mkdir /tmp/"@I30@	Rohidekar, Tarabai Venkatesh"
mkdir /tmp/"@I42@	Rohidekar, Chmpakka"
mkdir /tmp/"@I54@	Rohidekar, Manjula"
mkdir /tmp/"@I409@	Halliyal, Nitesh"
mkdir /tmp/"@I187@	Sarnobat, Shreenath"
mkdir /tmp/"@I296@	Deshpande, Shweta"
mkdir /tmp/"@I199@	Krishna, Mahesh"
mkdir /tmp/"@I284@	Adya, Hayavadan"
mkdir /tmp/"@I163@	Sarnobat, Sujatha"
mkdir /tmp/"@I175@	null, Sudha"
mkdir /tmp/"@I151@	Sarnobat, Arun"
mkdir /tmp/"@I272@	Deshpande, Priya"
mkdir /tmp/"@I393@	Ghatigar, Madhuri"
mkdir /tmp/"@I260@	Deshpande, Padma(?) / Nisha?"
mkdir /tmp/"@I381@	Kulkarni, Bharti"
mkdir /tmp/"@I61@	null, Sarala"
mkdir /tmp/"@I73@	Bengeri, Amit"
mkdir /tmp/"@I85@	"
mkdir /tmp/"@I97@	"
mkdir /tmp/"@I176@	Sarnobat, Aarthi"
mkdir /tmp/"@I285@	Adya, Chennakeshav"
mkdir /tmp/"@I188@	Sarnobat, Vaishnavi"
mkdir /tmp/"@I273@	Sholapurkar / Kalakukar?, Sanjeev"
mkdir /tmp/"@I394@	Ghatigar, Laxmi"
mkdir /tmp/"@I152@	Sarnobat, Kunda"
mkdir /tmp/"@I164@	Naik, Rajan"
mkdir /tmp/"@I297@	Deshpande, Shilpa"
mkdir /tmp/"@I140@	Nagsampige, Vasant"
mkdir /tmp/"@I261@	Deshpande, Rekha"
mkdir /tmp/"@I382@	Kulkarni, Chaaya"
mkdir /tmp/"@I370@	null, Geeta"
mkdir /tmp/"@I60@	null, Sulabha"
mkdir /tmp/"@I72@	Bengeri, Megha"
mkdir /tmp/"@I84@	null, Sagar"
mkdir /tmp/"@I96@	"
mkdir /tmp/"@I185@	Sarnobat, Vinayak"
mkdir /tmp/"@I197@	Gathikar, Tejas"
mkdir /tmp/"@I161@	null, Shubha"
mkdir /tmp/"@I270@	null, Veena"
mkdir /tmp/"@I391@	Naik, Nandini"
mkdir /tmp/"@I173@	Sarnobat, Aloke"
mkdir /tmp/"@I294@	Kulkarni, Meena"
mkdir /tmp/"@I282@	Shah, Anaya"
mkdir /tmp/"@I99@	"
mkdir /tmp/"@I51@	Rohidekar, Prema"
mkdir /tmp/"@I63@	null, Pushpa"
mkdir /tmp/"@I75@	Gombi, Sindhu"
mkdir /tmp/"@I87@	"
mkdir /tmp/"@I1@	Sarnobat, Sridhar"
mkdir /tmp/"@I198@	null, Bhumika"
mkdir /tmp/"@I295@	Deshpande, null"
mkdir /tmp/"@I174@	Sarnobat, Anjali"
mkdir /tmp/"@I186@	"
mkdir /tmp/"@I150@	Sarnobat, Madhukar"
mkdir /tmp/"@I380@	Kulkarni, Gopalrao N"
mkdir /tmp/"@I162@	Sarnobat, Sunil"
mkdir /tmp/"@I283@	Deshpande, Mangala"
mkdir /tmp/"@I271@	Deshpande, Preeti"
mkdir /tmp/"@I392@	Ghatigar, Srinivas B"
mkdir /tmp/"@I50@	Rohidekar, Jayaraj"
mkdir /tmp/"@I62@	null, Jyothi"
mkdir /tmp/"@I74@	Gombi, Soudamini"
mkdir /tmp/"@I86@	"
mkdir /tmp/"@I98@	"
mkdir /tmp/""
mkdir /tmp/"(477 rows)"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"TODO: why are the latest generation missing?"
mkdir /tmp/"Ancestors "
mkdir /tmp/"Ancestors /Balkrishna Sarnobat"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  "
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Ramchandra Sarnobat  Ambikha Deshpande, Sitabai"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Ramchandra Sarnobat  Ambikha Deshpande, Sitabai/Madhukar Sarnobat  null, Sudha"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Ramchandra Sarnobat  Ambikha Deshpande, Sitabai/Madhukar Sarnobat  null, Sudha/Anjali Sarnobat  Sarnobat, Anjali"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Ramchandra Sarnobat  Ambikha Deshpande, Sitabai/Madhukar Sarnobat  null, Sudha/Anjali Sarnobat  Sarnobat, Anjali/Nitesh Halliyal"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Ramchandra Sarnobat  Ambikha Deshpande, Sitabai/Madhukar Sarnobat  null, Sudha/Aarthi Sarnobat  Sarnobat, Aarthi"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Ramchandra Sarnobat  Ambikha Deshpande, Sitabai/Madhukar Sarnobat  null, Sudha/Aarthi Sarnobat  Sarnobat, Aarthi/Mohit Gathikar"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Ramchandra Sarnobat  Ambikha Deshpande, Sitabai/Madhukar Sarnobat  null, Sudha/Aarthi Sarnobat  Sarnobat, Aarthi/Tejas Gathikar"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Ramchandra Sarnobat  Ambikha Deshpande, Sitabai/Madhukar Sarnobat  null, Sudha/Anupama Sarnobat  Sarnobat, Anupama"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Ramchandra Sarnobat  Ambikha Deshpande, Sitabai/Madhukar Sarnobat  null, Sudha/Anupama Sarnobat  Sarnobat, Anupama/Bhumika "
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Ramchandra Sarnobat  Ambikha Deshpande, Sitabai/Arun Sarnobat  Kulkarni, Aruna"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Ramchandra Sarnobat  Ambikha Deshpande, Sitabai/Arun Sarnobat  Kulkarni, Aruna/Ankur Sarnobat  null, Pallavi"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Ramchandra Sarnobat  Ambikha Deshpande, Sitabai/Arun Sarnobat  Kulkarni, Aruna/Ankur Sarnobat  null, Pallavi/Rucha Sarnobat"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Ramchandra Sarnobat  Ambikha Deshpande, Sitabai/Arun Sarnobat  Kulkarni, Aruna/Ankur Sarnobat  null, Pallavi/Sachi Sarnobat"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Ramchandra Sarnobat  Ambikha Deshpande, Sitabai/Arun Sarnobat  Kulkarni, Aruna/Purnima Sarnobat  Sarnobat, Purnima"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Ramchandra Sarnobat  Ambikha Deshpande, Sitabai/Arun Sarnobat  Kulkarni, Aruna/Purnima Sarnobat  Sarnobat, Purnima/Megh Deshmukh"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Ramchandra Sarnobat  Ambikha Deshpande, Sitabai/Arun Sarnobat  Kulkarni, Aruna/Purnima Sarnobat  Sarnobat, Purnima/Sawani Deshmukh"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Ramchandra Sarnobat  Ambikha Deshpande, Sitabai/Uday Sarnobat  Kulkarni, Savita"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Ramchandra Sarnobat  Ambikha Deshpande, Sitabai/Uday Sarnobat  Kulkarni, Savita/Sachin Sarnobat  Dariano, Lucia"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Ramchandra Sarnobat  Ambikha Deshpande, Sitabai/Uday Sarnobat  Kulkarni, Savita/Aloke Sarnobat"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Ramchandra Sarnobat  Ambikha Deshpande, Sitabai/Sharad Sarnobat  Kari, Suman"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Ramchandra Sarnobat  Ambikha Deshpande, Sitabai/Sharad Sarnobat  Kari, Suman/Vandana Sarnobat  Sarnobat, Vandana"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Ramchandra Sarnobat  Ambikha Deshpande, Sitabai/Sharad Sarnobat  Kari, Suman/Vandana Sarnobat  Sarnobat, Vandana/Shreya "
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Ramchandra Sarnobat  Ambikha Deshpande, Sitabai/Sharad Sarnobat  Kari, Suman/Vandana Sarnobat  Sarnobat, Vandana/Shashank "
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Ramchandra Sarnobat  Ambikha Deshpande, Sitabai/Sharad Sarnobat  Kari, Suman/Vinayak Sarnobat"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Ramchandra Sarnobat  Ambikha Deshpande, Sitabai/Sudhir Sarnobat  Rohidekar, Meenakshi"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Ramchandra Sarnobat  Ambikha Deshpande, Sitabai/Sudhir Sarnobat  Rohidekar, Meenakshi/Sridhar Sarnobat"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Ramchandra Sarnobat  Ambikha Deshpande, Sitabai/Sudhir Sarnobat  Rohidekar, Meenakshi/Prakash Sarnobat"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Ramchandra Sarnobat  Ambikha Deshpande, Sitabai/Sudhir Sarnobat  Rohidekar, Meenakshi/Priya Sarnobat"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Ramchandra Sarnobat  Ambikha Deshpande, Sitabai/Kunda Sarnobat  Sarnobat, Kunda"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Balakrishna Sarnobat  null"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Balakrishna Sarnobat  null/Sarojini Sarnobat  Sarnobat, Sarojini"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Balakrishna Sarnobat  null/Sarojini Sarnobat  Sarnobat, Sarojini/"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Balakrishna Sarnobat  null/Sarojini Sarnobat  Sarnobat, Sarojini/(Mumbai)"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Balakrishna Sarnobat  null/Sarojini Sarnobat  Sarnobat, Sarojini/(Mumbai)"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Balakrishna Sarnobat  null/Vijay Sarnobat"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Balakrishna Sarnobat  null/Vilas Sarnobat"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Balakrishna Sarnobat  null/Babu Sarnobat"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Balakrishna Sarnobat  null/Sheelu Sarnobat (alive 2019, Miraj, Maharashtra)  Sarnobat (alive 2019, Miraj, Maharashtra), Sheelu"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Balakrishna Sarnobat  null/Sheelu Sarnobat (alive 2019, Miraj, Maharashtra)  Sarnobat (alive 2019, Miraj, Maharashtra), Sheelu/"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Balakrishna Sarnobat  null/Sheelu Sarnobat (alive 2019, Miraj, Maharashtra)  Sarnobat (alive 2019, Miraj, Maharashtra), Sheelu/"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Kamalabai ("Atya") Sarnobat  Sarnobat, Kamalabai ("Atya")"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Kamalabai ("Atya") Sarnobat  Sarnobat, Kamalabai ("Atya")/Choti "
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Kamalabai ("Atya") Sarnobat  Sarnobat, Kamalabai ("Atya")/Chabi "
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Kamalabai ("Atya") Sarnobat  Sarnobat, Kamalabai ("Atya")/Shalu "
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Kamalabai ("Atya") Sarnobat  Sarnobat, Kamalabai ("Atya")/Shamu Kulkarni"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Hanmanth Sarnobat  null, Shubha"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Hanmanth Sarnobat  null, Shubha/Sunil Sarnobat  "
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Hanmanth Sarnobat  null, Shubha/Sunil Sarnobat  /Shreenath Sarnobat"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Hanmanth Sarnobat  null, Shubha/Sunil Sarnobat  /Vaishnavi Sarnobat"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Hanmanth Sarnobat  null, Shubha/Sujatha Sarnobat  Sarnobat, Sujatha"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Hanmanth Sarnobat  null, Shubha/Sujatha Sarnobat  Sarnobat, Sujatha/Aditya Naik  null, Gayatri"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Hanmanth Sarnobat  null, Shubha/Sujatha Sarnobat  Sarnobat, Sujatha/Vikram Naik"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Kunja Sarnobat  Sarnobat, Kunja"
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Kunja Sarnobat  Sarnobat, Kunja/Aasha "
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Kunja Sarnobat  Sarnobat, Kunja/Lata "
mkdir /tmp/"Ancestors /Balkrishna Sarnobat/Dattatraya Sarnobat  null, Mother of Balakrishna  /Kunja Sarnobat  Sarnobat, Kunja/Maya "
mkdir /tmp/"Ancestors /Sadashiv Sarnobat  null"
mkdir /tmp/"Ancestors /Sadashiv Sarnobat  null/Neeelkanthand Sarnobat  null"
mkdir /tmp/"Ancestors /Sadashiv Sarnobat  null/Neeelkanthand Sarnobat  null/Vishnu Sarnobat  null"
mkdir /tmp/"Ancestors /Sadashiv Sarnobat  null/Neeelkanthand Sarnobat  null/Vishnu Sarnobat  null/Vitthal Sarnobat  null"
mkdir /tmp/"Ancestors /Sadashiv Sarnobat  null/Neeelkanthand Sarnobat  null/Vishnu Sarnobat  null/Vitthal Sarnobat  null/Milind Sarnobat  null"
mkdir /tmp/"Ancestors /Sadashiv Sarnobat  null/Neeelkanthand Sarnobat  null/Vishnu Sarnobat  null/Vitthal Sarnobat  null/Milind Sarnobat  null/Hemal Sarnobat"
mkdir /tmp/"Ancestors /Sadashiv Sarnobat  null/Neeelkanthand Sarnobat  null/Vishnu Sarnobat  null/Vitthal Sarnobat  null/Milind Sarnobat  null/Adwait Sarnobat"
mkdir /tmp/"Ancestors /Sadashiv Sarnobat  null/Neeelkanthand Sarnobat  null/Vishnu Sarnobat  null/Vitthal Sarnobat  null/Milind Sarnobat  null/Anuja Sarnobat"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Srinivas (Bapusaheb) Sarnobat  Kulkarni, Padmavati"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Srinivas (Bapusaheb) Sarnobat  Kulkarni, Padmavati/Ramesh Sarnobat  Dabeer, Nutan"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Srinivas (Bapusaheb) Sarnobat  Kulkarni, Padmavati/Ramesh Sarnobat  Dabeer, Nutan/Sayee Kar Sarnobat"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Srinivas (Bapusaheb) Sarnobat  Kulkarni, Padmavati/Ramesh Sarnobat  Dabeer, Nutan/Rahi Sarnobat"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Srinivas (Bapusaheb) Sarnobat  Kulkarni, Padmavati/Umesh Sarnobat  Shrikhande, Ina"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Srinivas (Bapusaheb) Sarnobat  Kulkarni, Padmavati/Umesh Sarnobat  Shrikhande, Ina/Rahul Sarnobat"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Srinivas (Bapusaheb) Sarnobat  Kulkarni, Padmavati/Umesh Sarnobat  Shrikhande, Ina/Ishan Sarnobat"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Manohar Sarnobat  Kulkarni (Jugul), Mandakini"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Manohar Sarnobat  Kulkarni (Jugul), Mandakini/Deepak Sarnobat  null"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Manohar Sarnobat  Kulkarni (Jugul), Mandakini/Nithin Sarnobat  null"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Manohar Sarnobat  Kulkarni (Jugul), Mandakini/Meena Sarnobat"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Manohar Sarnobat  Kulkarni (Jugul), Mandakini/Kalpana Sarnobat"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Sriram (Appasaheb) Sarnobat  Deshpande, Prema (Karguppi)"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Konher (Tatyasaheb) Sarnobat  Kulkarni, Ujwala (Tippurli)"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Konher (Tatyasaheb) Sarnobat  Kulkarni, Ujwala (Tippurli)/Vithal Sarnobat  null, Medha"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Konher (Tatyasaheb) Sarnobat  Kulkarni, Ujwala (Tippurli)/Vithal Sarnobat  null, Medha/Shivani Sarnobat  Sarnobat, Shivani"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Konher (Tatyasaheb) Sarnobat  Kulkarni, Ujwala (Tippurli)/Damodar Sarnobat  null, Kshama"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Konher (Tatyasaheb) Sarnobat  Kulkarni, Ujwala (Tippurli)/Damodar Sarnobat  null, Kshama/Kedar Sarnobat"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Konher (Tatyasaheb) Sarnobat  Kulkarni, Ujwala (Tippurli)/Anjali Sarnobat  Sarnobat, Anjali"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Konher (Tatyasaheb) Sarnobat  Kulkarni, Ujwala (Tippurli)/Anjali Sarnobat  Sarnobat, Anjali/Kaustub Desai  null, Yashraj"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Konher (Tatyasaheb) Sarnobat  Kulkarni, Ujwala (Tippurli)/Shruti Sarnobat  Sarnobat, Shruti"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Konher (Tatyasaheb) Sarnobat  Kulkarni, Ujwala (Tippurli)/Shruti Sarnobat  Sarnobat, Shruti/Shreyas Jinralkar  null, Aarya"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Shrikrishna Sarnobat  Adke, Radha (Sadalga)"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Shrikrishna Sarnobat  Adke, Radha (Sadalga)/Bhakti Sarnobat  Sarnobat, Bhakti"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Shrikrishna Sarnobat  Adke, Radha (Sadalga)/Bhakti Sarnobat  Sarnobat, Bhakti/Shubhan Hampiholi"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Shrikrishna Sarnobat  Adke, Radha (Sadalga)/Pushpa Sarnobat  Sarnobat, Pushpa"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Bhagwant Sarnobat  Kulkarni, (Ammangi)"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Bhagwant Sarnobat  Kulkarni, (Ammangi)/Kirti Sarnobat  Sarnobat, Kirti"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Bhagwant Sarnobat  Kulkarni, (Ammangi)/Sudhavshu Sarnobat"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Gajanan (Pandit) Sarnobat  Kanago, Shilpa  null, Geeta"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Gajanan (Pandit) Sarnobat  Kanago, Shilpa  null, Geeta/Shivram Sarnobat"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Gajanan (Pandit) Sarnobat  Kanago, Shilpa  null, Geeta/Trupti Sarnobat"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Ravi Sarnobat  Gosavi, Ashwini (Hattargi)"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Ravi Sarnobat  Gosavi, Ashwini (Hattargi)/Annapurna Sarnobat  Sarnobat, Annapurna"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Ravi Sarnobat  Gosavi, Ashwini (Hattargi)/Anulekha Sarnobat"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Venkatesh Sarnobat  Kulkarni, Gouri (Hubli)"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Venkatesh Sarnobat  Kulkarni, Gouri (Hubli)/Vaishnavi Sarnobat"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Venkatesh Sarnobat  Kulkarni, Gouri (Hubli)/Sankalp Sarnobat"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Vijaya Sarnobat  Sarnobat, Vijaya"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Vijaya Sarnobat  Sarnobat, Vijaya/Bharti Kulkarni  Kulkarni, Bharti"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Vijaya Sarnobat  Sarnobat, Vijaya/Bharti Kulkarni  Kulkarni, Bharti/Nikhil Naik"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Vijaya Sarnobat  Sarnobat, Vijaya/Bharti Kulkarni  Kulkarni, Bharti/Nandini Naik"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Vijaya Sarnobat  Sarnobat, Vijaya/Chaaya Kulkarni  Kulkarni, Chaaya"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Vijaya Sarnobat  Sarnobat, Vijaya/Chaaya Kulkarni  Kulkarni, Chaaya/Neeta Deshpande"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Vijaya Sarnobat  Sarnobat, Vijaya/Chaaya Kulkarni  Kulkarni, Chaaya/Nisha Deshpande"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Vijaya Sarnobat  Sarnobat, Vijaya/Prashant Kulkarni  null, Rashmi"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Vijaya Sarnobat  Sarnobat, Vijaya/Prashant Kulkarni  null, Rashmi/Varun Kulkarni"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Shashikala Sarnobat  Sarnobat, Shashikala"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Shashikala Sarnobat  Sarnobat, Shashikala/Madhuri Ghatigar  Ghatigar, Madhuri"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Shashikala Sarnobat  Sarnobat, Shashikala/Madhuri Ghatigar  Ghatigar, Madhuri/Khatavkar"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Shashikala Sarnobat  Sarnobat, Shashikala/Laxmi Ghatigar  Ghatigar, Laxmi"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Shashikala Sarnobat  Sarnobat, Shashikala/Laxmi Ghatigar  Ghatigar, Laxmi/"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Shashikala Sarnobat  Sarnobat, Shashikala/Gouri Ghatigar  Ghatigar, Gouri"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Shashikala Sarnobat  Sarnobat, Shashikala/Gouri Ghatigar  Ghatigar, Gouri/Gajbar"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Shashikala Sarnobat  Sarnobat, Shashikala/Geeta Ghatigar  Ghatigar, Geeta"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Shashikala Sarnobat  Sarnobat, Shashikala/Ramakrishna Ghatigar"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Leela Sarnobat  Sarnobat, Leela"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Leela Sarnobat  Sarnobat, Leela/Rajat Katti  null, Yamuna"
mkdir /tmp/"Ancestors /Damodar Sripad Sarnobat  null  null, Rama  Donwad, Sushila/Leela Sarnobat  Sarnobat, Leela/Rajat Katti  null, Yamuna/Kris Katti"
mkdir /tmp/""
